/* 周公解梦 · THE DREAM KEY — the dictionary of the night
   All interpretations composed for this showcase in the classical 周公解梦 register.
   Not transcribed from any single copyrighted edition.
   fields: z 中文 · e English · p pinyin · c category · o omen(ji吉/xiong凶/ping平)
           k extra search keys · cls classical 中文 line · rd English rendering
           md modern "another way to see it" · s star(famous) */

window.DREAM_CATS = [
  { c:"animals",   zh:"动物", en:"Animals",        gl:"🐍", note:"beasts, birds, fish, the creatures that walk through sleep" },
  { c:"plants",    zh:"植物", en:"Plants",         gl:"🌸", note:"trees, flowers, grain — what roots and what blooms" },
  { c:"people",    zh:"人物", en:"People",         gl:"👤", note:"kin and strangers, the living and the far-away" },
  { c:"nature",    zh:"自然", en:"Nature · Sky",   gl:"🌙", note:"weather, water, sun and moon, mountain and star" },
  { c:"body",      zh:"身体", en:"The Body",        gl:"🦷", note:"hair, teeth, blood — the self made flesh" },
  { c:"objects",   zh:"物品", en:"Objects",        gl:"🪙", note:"coin and mirror, coffin and cloth, the things of the hand" },
  { c:"buildings", zh:"建筑", en:"Buildings",      gl:"🏛", note:"house, gate, bridge, tomb — the architecture of the dream" },
  { c:"lifedeath", zh:"生死", en:"Life & Death",   gl:"⚰", note:"birth, wedding, illness, the coffin and the grave" },
  { c:"spirits",   zh:"鬼神", en:"Spirits & Gods", gl:"👻", note:"ghosts, gods, dragons, the ancestors who return" },
  { c:"emotions",  zh:"情感", en:"Feeling",         gl:"💗", note:"weeping and laughter, love, fear, the weather of the heart" },
  { c:"actions",   zh:"行为", en:"Actions",         gl:"🕊", note:"to fly, to fall, to be chased, to lose a tooth" }
];

window.DREAMS = [
/* ============================ 动物 ANIMALS ============================ */
{ z:"蛇", e:"Snake", p:"shé", c:"animals", o:"ji", s:1, k:"serpent viper 龙蛇 snake bite",
  cls:"蛇入怀中，主生贵子；蛇随人行，主迁居得财。",
  rd:"A snake that slips into your robe promises a child of note; one that follows at your heel foretells a move, and coin arriving with it.",
  md:"The snake is the mind's oldest tenant — dread and vitality wound into one cold rope. Ask less what it means and more what you have been keeping at arm's length." },
{ z:"龙", e:"Dragon", p:"lóng", c:"animals", o:"ji", s:1, k:"loong wyrm 神龙 flying dragon",
  cls:"梦乘龙上天，大贵之兆；龙入水门，主官禄至。",
  rd:"To ride a dragon into the sky is the sign of high honour; a dragon entering by the water-gate brings office and salary to the house.",
  md:"Dragons in dreams are rarely about luck and almost always about scale. What would you attempt if you simply assumed you were meant to rise?" },
{ z:"虎", e:"Tiger", p:"hǔ", c:"animals", o:"ping", k:"tiger beast 猛虎 white tiger",
  cls:"虎入门庭，主威权临身；与虎相搏而胜，主克敌成名。",
  rd:"A tiger crossing the threshold lays authority on your shoulders; to wrestle one and win is to master a rival and be spoken of.",
  md:"The tiger is the part of you that could be dangerous if you let it. Dreaming it prowl close often means you have been asking a fierce thing to sit very still." },
{ z:"马", e:"Horse", p:"mǎ", c:"animals", o:"ji", k:"horse steed 骏马 riding gallop",
  cls:"乘马奔驰，所求皆遂；马生驹，主家业兴旺。",
  rd:"To ride a galloping horse is to have your errands granted; a mare foaling foretells the household's fortunes widening.",
  md:"The horse is momentum you don't have to manufacture. Where in waking life are you ready to be carried rather than to push?" },
{ z:"牛", e:"Ox · Cow", p:"niú", c:"animals", o:"ji", k:"ox cow cattle 黄牛 buffalo",
  cls:"牛上高山，大吉；黄牛入宅，主有喜庆临门。",
  rd:"An ox climbing the high mountain is a great and open omen; a yellow ox entering the yard brings a season of celebration.",
  md:"Slow, patient strength. The ox rewards the dreamer who has been mistaking speed for progress." },
{ z:"鱼", e:"Fish", p:"yú", c:"animals", o:"ji", s:1, k:"fish carp 鲤鱼 school of fish water",
  cls:"群鱼游水，主财帛丰盈；梦得大鱼，主名利双收。",
  rd:"A school of fish threading the water foretells wealth in abundance; to land a great fish is to gather both name and profit.",
  md:"Fish move in the deep water of feeling. A shoal of them can mean your intuitions are running healthy and plentiful — trust the ones that keep returning." },
{ z:"凤凰", e:"Phoenix", p:"fèng huáng", c:"animals", o:"ji", k:"phoenix fenghuang 鸾凤 firebird",
  cls:"凤凰入室，主大贵之喜；凤鸣朝阳，主吉庆盈门。",
  rd:"A phoenix alighting in the room foretells great honour; its cry to the rising sun fills the doorway with good things.",
  md:"The phoenix arrives only after burning. Dreaming it can mean some ending you feared has quietly become a beginning." },
{ z:"鸟", e:"Bird", p:"niǎo", c:"animals", o:"ji", k:"bird sparrow flock 飞鸟 wing",
  cls:"众鸟飞集，主远方宾客至；鸟入怀中，主生贵女。",
  rd:"Birds gathering to roost foretell guests from far away; a bird nesting against your breast promises a daughter to be proud of.",
  md:"Birds are messages the waking mind hasn't opened yet. Notice which direction they fly from." },
{ z:"燕", e:"Swallow", p:"yàn", c:"animals", o:"ji", k:"swallow spring 燕子 nest eaves",
  cls:"燕来入宅，主远客将至，家道吉昌。",
  rd:"A swallow slipping under the eaves foretells a far guest coming near, and the house's fortunes turning kind.",
  md:"Swallows keep returning to the same eaves. The dream may be nudging you toward a loyalty you'd nearly given up on." },
{ z:"鹤", e:"Crane", p:"hè", c:"animals", o:"ji", k:"crane white 仙鹤 longevity heron",
  cls:"梦见白鹤翔空，主寿考绵长，德望日隆。",
  rd:"A white crane wheeling in the open sky foretells a long life and a name that quietly gathers weight.",
  md:"The crane is patience made beautiful. It tends to visit dreamers who have been in too much of a hurry to age well." },
{ z:"龟", e:"Tortoise", p:"guī", c:"animals", o:"ji", k:"turtle tortoise 神龟 shell longevity",
  cls:"龟入人家，主延年益寿，添福添丁。",
  rd:"A tortoise entering the household lengthens the years and adds both blessing and offspring.",
  md:"The tortoise carries its shelter with it. In dreams it can mean you already hold the security you keep searching outside yourself for." },
{ z:"鸡", e:"Rooster", p:"jī", c:"animals", o:"ping", k:"chicken rooster hen 公鸡 crow dawn",
  cls:"闻鸡鸣，主吉事将至；怀中抱鸡，防口舌是非。",
  rd:"To hear the cock crow is a good thing drawing near; to hold a hen in your arms, guard against gossip and quarrels.",
  md:"The rooster wakes the house whether or not it is ready. Some truth in you is crowing for the dawn — the question is only whether you'll rise." },
{ z:"犬", e:"Dog", p:"quǎn", c:"animals", o:"ping", k:"dog hound 狗 bark loyal",
  cls:"犬吠不止，主口舌纷争；犬来迎人，主友信将至。",
  rd:"A dog that will not stop barking warns of quarrels; a dog running to greet you foretells word from a friend.",
  md:"The dog is loyalty in animal form — sometimes yours, sometimes another's. Whose devotion have you been taking for granted?" },
{ z:"猫", e:"Cat", p:"māo", c:"animals", o:"xiong", k:"cat feline 猫咪 mouse",
  cls:"猫捕鼠雀，虽得小利，须防暗盗小人。",
  rd:"A cat taking mouse or sparrow brings a little gain, but warns of a quiet thief among those you trust.",
  md:"The cat keeps its own counsel. Dreaming it may mirror a part of you that has grown self-sufficient — or a friend who has grown remote." },
{ z:"猪", e:"Pig", p:"zhū", c:"animals", o:"ji", k:"pig boar hog 肥猪 swine",
  cls:"群猪满栏，主大发其财；猪入宅中，主财喜双至。",
  rd:"A sty full of pigs foretells wealth in great measure; a pig wandering into the house brings both money and joy.",
  md:"Abundance without pretension. The pig blesses the dreamer who has stopped being embarrassed to want plenty." },
{ z:"羊", e:"Sheep · Goat", p:"yáng", c:"animals", o:"ji", k:"sheep goat lamb 绵羊 flock",
  cls:"牵羊而行，主得贵人扶助；群羊满野，主家资丰足。",
  rd:"To lead a sheep along the road is to gain a patron's help; a field of them foretells a well-stocked house.",
  md:"The flock moves together or not at all. Dreaming of sheep can ask whether you're finding safety in belonging, or losing yourself in it." },
{ z:"兔", e:"Rabbit", p:"tù", c:"animals", o:"ji", k:"rabbit hare 白兔 moon",
  cls:"梦见白兔当门，主子孙昌盛，家宅安宁。",
  rd:"A white rabbit at the door foretells thriving children and a quiet, well-kept home.",
  md:"The moon's own rabbit, gentle and quick. It tends to appear when the dreamer needs permission to be soft." },
{ z:"鼠", e:"Mouse · Rat", p:"shǔ", c:"animals", o:"xiong", k:"rat mouse 老鼠 gnaw rodent",
  cls:"鼠咬衣物，主有小人暗算；群鼠乱窜，主家宅不宁。",
  rd:"A mouse gnawing your clothes warns of a schemer at work; rats scattering through the room mean the house is uneasy.",
  md:"Small erosions. The rat dream often points not at one large threat but at many little compromises nibbling at something you value." },
{ z:"蝴蝶", e:"Butterfly", p:"hú dié", c:"animals", o:"ji", s:1, k:"butterfly moth 蝴 zhuangzi dream 庄周",
  cls:"梦见蝴蝶翩跹，主心事将解，忧愁化喜。",
  rd:"A butterfly turning on the air foretells a knotted worry loosening, and grief changing quietly into gladness.",
  md:"Zhuangzi dreamed he was a butterfly and woke unsure which of them was dreaming. The butterfly asks the softest of questions: how certain are you that this is the waking life?" },
{ z:"蜘蛛", e:"Spider", p:"zhī zhū", c:"animals", o:"ji", k:"spider web 蛛网 weave",
  cls:"蛛垂当面，主喜事临门；见蛛结网，主财源渐聚。",
  rd:"A spider let down before your face foretells joy at the door; one weaving its web means income slowly gathering.",
  md:"The spider makes a home out of patience and its own body. What are you weaving, thread by thread, that isn't finished enough to be seen yet?" },
{ z:"蜂", e:"Bee", p:"fēng", c:"animals", o:"ping", k:"bee wasp 蜜蜂 sting swarm honey",
  cls:"蜂来采花，主小财可得；群蜂螫人，主劳碌招怨。",
  rd:"A bee working the blossoms brings a small profit; a swarm that stings warns of toil that earns you resentment.",
  md:"The bee is industry that can turn to fury. Dreaming of the swarm may ask where your hard work has curdled into something that hurts to be near." },
{ z:"蝉", e:"Cicada", p:"chán", c:"animals", o:"ji", k:"cicada 知了 summer song shell",
  cls:"闻蝉鸣于高树，主声名远播，脱旧更新。",
  rd:"To hear the cicada sing high in the tree foretells a name that carries — and an old shell left behind.",
  md:"The cicada spends years in the dark to sing for a single summer. The dream may be honouring a long, unseen wait that is almost over." },

/* ============================ 植物 PLANTS ============================ */
{ z:"树", e:"Tree", p:"shù", c:"plants", o:"ji", s:1, k:"tree big 大树 forest trunk root",
  cls:"大树参天，主根基稳固，庇荫子孙；枯木逢春，主否极泰来。",
  rd:"A great tree reaching skyward means a firm foundation and shade for those who come after; a dead tree greening again means the worst has turned toward the best.",
  md:"The tree keeps the shape of every year it has lived. Dreaming one may ask you to look at how far your own roots have quietly spread." },
{ z:"花", e:"Flower", p:"huā", c:"plants", o:"ji", k:"flower blossom 鲜花 bloom garden",
  cls:"百花齐放，主喜庆将至；花开满树，主子孙荣显。",
  rd:"Flowers opening all at once foretell an approaching joy; a tree in full bloom promises children who bring honour.",
  md:"A blossom is a plant's most public feeling. What in you is finally ready to be seen in colour?" },
{ z:"梅", e:"Plum Blossom", p:"méi", c:"plants", o:"ji", k:"plum blossom winter 梅花 snow",
  cls:"梅开雪中，主苦尽甘来，清名自守。",
  rd:"Plum blossom opening in the snow foretells sweetness after hardship, and a clean name kept through cold.",
  md:"The plum flowers before anything else dares to. Dreaming it can mean your courage is a season ahead of your circumstances." },
{ z:"莲", e:"Lotus", p:"lián", c:"plants", o:"ji", k:"lotus water 荷花 pond pure mud",
  cls:"莲出清池，主贵子降生，出污不染。",
  rd:"A lotus rising from the clear pool foretells the birth of a fine child, and a purity that mud could not touch.",
  md:"The lotus needs the mud to bloom. The dream may be reconciling you to a difficult origin you've been trying to disown." },
{ z:"竹", e:"Bamboo", p:"zhú", c:"plants", o:"ji", k:"bamboo 竹子 grove segment upright",
  cls:"竹生新笋，主添丁进口，节节高升。",
  rd:"Bamboo throwing up new shoots foretells more mouths at the table and a rise that climbs by joints.",
  md:"Bamboo is strong because it is hollow and bends. The dream may prize the flexibility you've been mistaking for weakness." },
{ z:"松", e:"Pine", p:"sōng", c:"plants", o:"ji", k:"pine evergreen 松树 longevity green",
  cls:"松柏常青，主寿元绵永，志节不移。",
  rd:"Pine and cypress staying green foretell a long span of years and a resolve that does not shift with weather.",
  md:"The pine keeps its colour through the killing cold. It visits dreamers who need reminding that constancy is its own kind of triumph." },
{ z:"柳", e:"Willow", p:"liǔ", c:"plants", o:"ping", k:"willow 柳树 parting spring branch",
  cls:"柳条垂绿，主离别又逢；折柳赠人，主远行难留。",
  rd:"Willow trailing its green foretells a parting and a reunion both; to break a willow branch and give it away means a leaving that cannot be held back.",
  md:"The willow bends with every wind and survives them all. The dream may be teaching you a softer way to grieve a goodbye." },
{ z:"桃", e:"Peach", p:"táo", c:"plants", o:"ji", k:"peach fruit blossom 桃子 immortal",
  cls:"食桃味甘，主延年得寿；桃花盛开，主姻缘将至。",
  rd:"A sweet peach eaten foretells added years; peach blossom in full flush foretells a marriage drawing near.",
  md:"The peach is the fruit of long life and of romance both. The dream may not be able to tell you which — only that something ripe is arriving." },
{ z:"果", e:"Fruit", p:"guǒ", c:"plants", o:"ji", k:"fruit harvest ripe 果实 orchard",
  cls:"树果累累，主谋事有成，收获在望。",
  rd:"Boughs heavy with fruit foretell a venture bearing out, and a harvest close at hand.",
  md:"Fruit is the long ago made edible. The dream may be telling you something you planted and forgot is ready to be eaten." },
{ z:"稻", e:"Rice · Grain", p:"dào", c:"plants", o:"ji", k:"rice grain harvest 稻谷 field wheat",
  cls:"稻谷满仓，主家道富足，衣食无忧。",
  rd:"Grain filling the barn foretells a household made rich, with neither food nor cloth to worry over.",
  md:"Grain is patience turned to plenty. The dream may be asking you to trust the slow accumulation you can't yet see the total of." },
{ z:"草", e:"Grass", p:"cǎo", c:"plants", o:"ping", k:"grass weeds 青草 meadow green",
  cls:"青草丛生，主小人渐多，须勤修剪；草木回青，主时运转佳。",
  rd:"Grass thickening underfoot warns that small troubles multiply and must be cut back; the same green returning to bare ground means fortune turning.",
  md:"Grass grows wherever it is allowed. The dream may ask what you've stopped tending, and what has crept in to fill the gap." },
{ z:"根", e:"Root", p:"gēn", c:"plants", o:"ji", k:"root deep 树根 ground foundation",
  cls:"见根深入土，主基业稳固，家运绵长。",
  rd:"Roots driving deep into the earth foretell a foundation that holds, and a family fortune that runs long.",
  md:"Roots do their work entirely in the dark. The dream may be honouring effort no one has thanked you for — least of all yourself." },
{ z:"落叶", e:"Falling Leaves", p:"luò yè", c:"plants", o:"ping", k:"leaves autumn fall 落叶 wither",
  cls:"落叶纷飞，主旧事将了，宜舍则舍。",
  rd:"Leaves coming down in numbers foretell an old matter ending — let go of what asks to be let go.",
  md:"The tree drops its leaves to survive the winter, not because they failed. What are you being asked to release so the rest of you can last?" },

/* ============================ 人物 PEOPLE ============================ */
{ z:"父母", e:"Parents", p:"fù mǔ", c:"people", o:"ji", k:"mother father 爸妈 parents family elder",
  cls:"梦见父母，主福荫在身；父母安坐，主家宅平安。",
  rd:"To dream of your parents means their blessing rests on you; to see them seated at ease foretells peace in the house.",
  md:"We dream our parents long after they have stopped being only themselves. Whoever they were, in sleep they often stand in for whatever we still want permission from." },
{ z:"孩子", e:"Child", p:"hái zi", c:"people", o:"ji", k:"child baby son daughter 小孩 kid infant",
  cls:"梦抱婴孩，主喜事临门，新机将启。",
  rd:"To hold an infant in your arms foretells a joy at the door and a new venture about to open.",
  md:"The child in a dream is often the newest part of you — a plan, a hope, a self only just born and easily dropped. Handle it the way you'd want to be handled when new." },
{ z:"故人", e:"An Old Friend", p:"gù rén", c:"people", o:"ping", k:"friend old acquaintance 朋友 reunion far",
  cls:"梦见故人来访，主远信将至，旧缘复续。",
  rd:"An old friend coming to call foretells word from afar and a bond thought over quietly resuming.",
  md:"The people who visit our sleep uninvited are rarely there for their own sake. What did that friendship carry that you've been missing?" },
{ z:"陌生人", e:"A Stranger", p:"mò shēng rén", c:"people", o:"ping", k:"stranger unknown 陌生 faceless",
  cls:"梦遇陌生之人，主贵人潜近，或有新交。",
  rd:"To meet a stranger in sleep foretells a helper drawing near unseen, or a new acquaintance soon to come.",
  md:"Every stranger in a dream wears your own face somewhere underneath. Ask what part of you you haven't been introduced to yet." },
{ z:"帝王", e:"An Emperor", p:"dì wáng", c:"people", o:"ji", k:"emperor king ruler 皇帝 official authority",
  cls:"梦见帝王召见，主得贵人提拔，功名可期。",
  rd:"To be summoned before an emperor foretells the lift of a powerful patron, and honours worth hoping for.",
  md:"The figure of great authority in a dream measures your own relationship to power. Do you approach the throne to serve it, to please it, or to sit in it?" },
{ z:"僧道", e:"A Monk", p:"sēng dào", c:"people", o:"ji", k:"monk priest sage 和尚 道士 holy",
  cls:"梦见僧道谈玄，主烦恼渐消，心境澄明。",
  rd:"A monk or Daoist speaking of deep things foretells troubles thinning, and a mind turning clear.",
  md:"The wise stranger in the dream is the counsel you already hold but won't say to yourself aloud. Listen for the sentence you'd rather ignore." },
{ z:"医者", e:"A Physician", p:"yī zhě", c:"people", o:"ji", k:"doctor healer physician 医生 cure",
  cls:"梦见良医诊脉，主宿疾将愈，忧患得解。",
  rd:"A good physician taking your pulse foretells a long ailment lifting and a worry finding its cure.",
  md:"The healer arrives in dreams when some part of you already knows what the treatment is. What have you been avoiding diagnosing?" },
{ z:"美人", e:"A Beautiful Person", p:"měi rén", c:"people", o:"ping", k:"beauty lover beautiful 美女 attraction",
  cls:"梦见美人相顾，主情缘可期，然须防虚花。",
  rd:"A lovely one meeting your eye foretells a promising affection — yet beware a flower with no fruit.",
  md:"Desire in a dream rarely wants only the person it shows you. Ask what quality they carry that you long to be nearer to in yourself." },
{ z:"仇人", e:"An Enemy", p:"chóu rén", c:"people", o:"ping", k:"enemy rival foe 仇敌 quarrel conflict",
  cls:"梦与仇人相见，主宿怨可解，或化敌为友。",
  rd:"To meet an enemy face to face foretells an old grudge that could dissolve — even a foe turning friend.",
  md:"We give our enemies house-room in our sleep more often than our friends. The dream may be asking whether the fight is still worth what it costs to keep." },
{ z:"群众", e:"A Crowd", p:"qún zhòng", c:"people", o:"ping", k:"crowd many people throng 人群 multitude",
  cls:"梦入闹市人群，主机遇纷来，亦防扰攘失神。",
  rd:"To enter a thronged marketplace foretells opportunities crowding in — and warns against losing your own centre in the press.",
  md:"A crowd in a dream is often the sound of every voice you've internalised. Which of them is actually yours?" },

/* ============================ 自然 NATURE / SKY ============================ */
{ z:"水", e:"Water", p:"shuǐ", c:"nature", o:"ji", s:1, k:"water river clear 河水 flood stream",
  cls:"清水盈盈，主财源广进；涉水而过，主诸事顺遂；浊水泛滥，则防破财。",
  rd:"Clear water brimming foretells wealth flowing in from many sides; to wade across and reach the far bank means all matters going smoothly; but muddy water in flood warns of loss.",
  md:"Water is feeling itself — clear or churned, contained or spilling. The dream is asking less what will happen and more how the tide of your own emotion is running." },
{ z:"火", e:"Fire", p:"huǒ", c:"nature", o:"ji", s:1, k:"fire flame burn 火焰 blaze bonfire",
  cls:"梦见大火熊熊，主家道兴旺，得财添丁；火光冲天，主运势正盛。",
  rd:"A great fire roaring foretells a flourishing house — wealth and children both; flames leaping to the sky mean your fortune is at its height.",
  md:"Fire in a dream is desire and destruction sharing one body. What have you been burning to do — and what are you afraid it would consume?" },
{ z:"月", e:"Moon", p:"yuè", c:"nature", o:"ji", s:1, k:"moon night 月亮 moonlight full moon",
  cls:"明月当空，主心愿得偿，贵人相助；月圆光满，主团圆之喜。",
  rd:"A bright moon riding high foretells a wish fulfilled and a patron's help; the full moon at its roundest foretells a reunion.",
  md:"The moon shows only the face it turns toward us and keeps the rest in dark. The dream may be about a wholeness you can sense but not yet see all of." },
{ z:"日", e:"Sun", p:"rì", c:"nature", o:"ji", k:"sun sunrise 太阳 dawn light",
  cls:"红日东升，主运程焕发，前程似锦；日光照身，主贵气加临。",
  rd:"A red sun rising in the east foretells fortune breaking open and a road ahead like brocade; sunlight falling on you means honour drawing near.",
  md:"The sun rises whether or not we are ready to be seen. The dream may be nudging some hidden part of you toward daylight." },
{ z:"星", e:"Stars", p:"xīng", c:"nature", o:"ji", k:"star sky night 星辰 constellation",
  cls:"众星拱月，主得众人拥戴；流星入怀，主贵子将生。",
  rd:"Stars circling the moon foretell the loyalty of many; a shooting star falling into your arms foretells a remarkable child to come.",
  md:"We steer by stars precisely because they are too far to reach. What guiding thing are you navigating toward that you never expect to arrive at?" },
{ z:"云", e:"Clouds", p:"yún", c:"nature", o:"ji", k:"cloud sky 云彩 mist auspicious",
  cls:"祥云缭绕，主福气临门；乘云而上，主平步青云。",
  rd:"Auspicious clouds curling round the house foretell blessing at the door; to ride a cloud upward means rising by easy steps.",
  md:"Clouds are water pretending to be architecture. The dream may be showing you how solid something looks that is really only passing through." },
{ z:"雨", e:"Rain", p:"yǔ", c:"nature", o:"ji", k:"rain storm 下雨 shower downpour",
  cls:"及时甘雨，主润泽万物，久旱逢生；细雨绵绵，主忧愁渐解。",
  rd:"A timely sweet rain foretells nourishment for all things, and life after long drought; a fine, unhurried rain means sorrow slowly easing.",
  md:"Rain is grief and relief wearing the same coat. Sometimes the dream lets you cry the weather you wouldn't allow yourself awake." },
{ z:"雪", e:"Snow", p:"xuě", c:"nature", o:"ji", k:"snow white winter 下雪 cold frost",
  cls:"瑞雪纷飞，主来年丰稔，喜事将临；雪覆山川，主一洗前愆。",
  rd:"Blessed snow coming down foretells a fat harvest next year and a joy approaching; snow blanketing the hills means old faults washed clean.",
  md:"Snow makes every ruined thing briefly beautiful and quiet. The dream may be offering a pause — a white page over a landscape you were tired of." },
{ z:"风", e:"Wind", p:"fēng", c:"nature", o:"ping", k:"wind gale breeze 大风 gust",
  cls:"和风徐来，主运势渐顺；狂风骤起，主变动将生，宜守勿躁。",
  rd:"A gentle wind coming on foretells fortune easing forward; a sudden gale means change is rising — hold steady, don't rush.",
  md:"Wind is the invisible made forceful. The dream may be naming a pressure in your life you can feel everywhere and point to nowhere." },
{ z:"雷", e:"Thunder", p:"léi", c:"nature", o:"ji", k:"thunder lightning storm 打雷 rumble",
  cls:"雷声震响，主威名远播，惊蛰而动；雷电交加，主积郁一发。",
  rd:"Thunder rolling out foretells a name that reaches far, and long-sleeping things waking to move; thunder and lightning together mean pent things finally breaking loose.",
  md:"Thunder is the sound arriving after the flash. The dream may be about a truth you already saw — now waiting for the noise of consequence." },
{ z:"山", e:"Mountain", p:"shān", c:"nature", o:"ji", k:"mountain climb peak 高山 summit",
  cls:"梦登高山，主志向高远，步步高升；山势巍峨，主靠山稳固。",
  rd:"To climb a high mountain foretells lofty aims and a step-by-step rise; a mountain standing massive means a firm support behind you.",
  md:"A mountain in a dream is an ambition you can see the whole shape of at once. That clarity is rare — don't waste it doubting the size of the thing." },
{ z:"海", e:"The Sea", p:"hǎi", c:"nature", o:"ji", k:"sea ocean 大海 waves vast",
  cls:"梦见大海，主胸襟开阔，前程无量；渡海平安，主大难得济。",
  rd:"To dream of the sea foretells a wide heart and a boundless road ahead; to cross it safely means a great trial survived.",
  md:"The sea is more than any one feeling can be. The dream may be asking you to make peace with something in you too vast to master — only to sail." },
{ z:"彩虹", e:"Rainbow", p:"cǎi hóng", c:"nature", o:"ji", k:"rainbow arch 彩虹 colour bridge",
  cls:"雨后见虹，主转危为安，好事将成。",
  rd:"A rainbow after the rain foretells danger turning to safety, and a good thing about to complete itself.",
  md:"The rainbow only appears where light and storm agree to occupy the same sky. The dream may be reconciling two things in you that you thought couldn't coexist." },

/* ============================ 身体 THE BODY ============================ */
{ z:"血", e:"Blood", p:"xuè", c:"body", o:"ji", s:1, k:"blood bleeding 出血 red vein",
  cls:"梦见出血，主得财帛；见血满地，主大财将至。",
  rd:"To see yourself bleed foretells the arrival of wealth; blood covering the ground foretells a great fortune coming.",
  md:"The old book calls blood a sign of gain, and it isn't wrong to sense life-force in it. A blood dream often marks something vital finally moving — costly, warm, and yours." },
{ z:"头发", e:"Hair", p:"tóu fà", c:"body", o:"ping", k:"hair loss grow 头发 haircut long",
  cls:"发长而黑，主健旺添寿；忽然落发，主忧思劳损，宜养精神。",
  rd:"Hair grown long and black foretells vigour and added years; hair suddenly falling means worry wearing you thin — tend your spirit.",
  md:"Hair is the self we style for others to read. Dreaming of losing it can mark a fear of losing face, or a quiet wish to be seen as you actually are." },
{ z:"眼睛", e:"Eyes", p:"yǎn jing", c:"body", o:"ping", k:"eye sight vision 眼睛 blind see",
  cls:"梦见明目，主见识开阔；目不能视，主受人蒙蔽，宜细察。",
  rd:"Bright, clear eyes foretell a widening understanding; eyes that cannot see warn of being deceived — look closer.",
  md:"The dream of eyes is the mind asking about its own seeing. What have you been refusing to look at directly?" },
{ z:"手", e:"Hands", p:"shǒu", c:"body", o:"ji", k:"hand fingers 手 grip arm",
  cls:"梦见双手洁净有力，主诸事得成，助力将至。",
  rd:"Two hands clean and strong foretell tasks brought to completion, and help arriving to work beside you.",
  md:"Hands are agency made visible. Dreaming them bound, dirty, or missing may be your own doubt about whether you can still do the thing." },
{ z:"心", e:"Heart", p:"xīn", c:"body", o:"ji", k:"heart chest 心脏 beat feeling",
  cls:"梦见心安而跳稳，主情志和顺，忧惧自消。",
  rd:"A heart beating calm and even foretells settled feeling and a fear that quietly dissolves.",
  md:"The heart in a dream keeps the honest count. If it raced, some matter in your life is running faster than you've admitted." },
{ z:"骨", e:"Bones", p:"gǔ", c:"body", o:"ping", k:"bone skeleton 骨头 frame",
  cls:"梦见白骨森然，主根基须固；见己骨强，主体健志坚。",
  rd:"Bare white bone foretells a foundation that needs shoring; to see your own frame strong means a sound body and a firm will.",
  md:"Bones are what remains when everything softer is gone. The dream may be showing you the structure of a thing — or a self — stripped to essentials." },
{ z:"孕", e:"Pregnancy", p:"yùn", c:"body", o:"ji", s:1, k:"pregnant belly 怀孕 baby expecting womb",
  cls:"梦见有孕，主福至将临，谋事有成，或添丁进口。",
  rd:"To dream you are with child foretells blessing on its way and ventures that will come to term — sometimes a real birth to follow.",
  md:"Pregnancy in a dream is almost always about becoming, not birth alone. What is growing in you that no one, including you, can quite see yet?" },
{ z:"病", e:"Illness", p:"bìng", c:"body", o:"ji", k:"sick disease 生病 ill fever",
  cls:"梦见己身患病，反主健康长久；病中得药，主转危为安。",
  rd:"To dream you have fallen ill oddly foretells lasting health; to be given medicine in the sickness means danger turning to safety.",
  md:"The dream of illness often surfaces what waking pride keeps hidden — a tiredness, a limit. Being unwell in sleep can be permission to finally rest." },
{ z:"泪", e:"Tears", p:"lèi", c:"body", o:"ji", k:"tears crying weep 眼泪 sob",
  cls:"梦见流泪，反主喜事将至，郁结得舒。",
  rd:"To weep in a dream, contrary to fear, foretells a joy approaching and a knot in the chest coming loose.",
  md:"Tears in sleep do the crying you were too busy or too proud for. Whatever leaked out, it needed to." },
{ z:"声音", e:"Voice", p:"shēng yīn", c:"body", o:"ping", k:"voice speak silent 声音 mute shout",
  cls:"梦中失声难言，主有话未尽，宜寻机直陈。",
  rd:"To lose your voice in a dream and struggle to speak means there is something unsaid — find the moment to say it plainly.",
  md:"The dream where you can't make a sound is one of the most common of all. It usually points to a truth you're carrying that has nowhere yet to go." },

/* ============================ 物品 OBJECTS ============================ */
{ z:"棺材", e:"Coffin", p:"guān cai", c:"objects", o:"ji", s:1, k:"coffin casket 棺 death promotion wealth",
  cls:"梦见棺材，主升官发财；棺入家门，主财禄双至。",
  rd:"To dream of a coffin foretells promotion and wealth — 官 and 财 share the sound; a coffin carried into the house brings both office and income.",
  md:"The book turns the coffin, of all things, into a sign of gain — because an ending cleared the ground for a rise. The dream may be dressing an opportunity in the costume of your fear." },
{ z:"粪", e:"Excrement", p:"fèn", c:"objects", o:"ji", s:1, k:"dung feces shit 屎 muck manure",
  cls:"梦见身沾粪秽，主大得财利；粪满其屋，主家资骤富。",
  rd:"To dream of being soiled with muck foretells a great gain of money; a house full of it means wealth arriving all at once.",
  md:"The tradition's most cheerful joke: the thing we most want to be rid of is the sign of fortune. The dream may be finding value in exactly what you've been calling waste." },
{ z:"钱", e:"Money", p:"qián", c:"objects", o:"ping", k:"money coin 金钱 cash gold wealth",
  cls:"梦见拾得金钱，主小利可获；散钱与人，反主财源广进。",
  rd:"To find money on the ground foretells a modest gain; to give money away, contrary to sense, foretells income widening.",
  md:"Money in a dream is rarely money. It's whatever you measure your worth or safety by. Watch whether you were hoarding it or letting it go." },
{ z:"镜", e:"Mirror", p:"jìng", c:"objects", o:"ping", k:"mirror reflection 镜子 glass face",
  cls:"梦见明镜照人，主自省得福；镜破，主夫妻分离，或事有变。",
  rd:"A clear mirror showing your face foretells blessing through self-knowledge; a broken mirror warns of a parting, or a matter that will not hold.",
  md:"The mirror in a dream returns the one face you can never see directly. Whatever it showed you, the dream trusted you could bear to look." },
{ z:"刀", e:"Knife · Blade", p:"dāo", c:"objects", o:"ping", k:"knife sword blade 刀剑 cut weapon",
  cls:"梦见持刀在手，主权柄可握，锐意进取；刀伤己身，则防口舌之厄。",
  rd:"A blade held firm in the hand foretells power you can wield and a sharp resolve; a knife that wounds you warns of injury by sharp words.",
  md:"The blade is decisiveness that can cut either way. The dream may be asking whether your edge is protecting you or cutting the people near you." },
{ z:"衣", e:"Clothing", p:"yī", c:"objects", o:"ji", k:"clothes robe dress 衣服 garment new",
  cls:"梦得新衣加身，主更换气象，喜事将临；衣破，主处境窘迫。",
  rd:"To be dressed in new clothes foretells a change of fortune and a joy approaching; torn clothing warns of straitened circumstances.",
  md:"Clothing is the self we present. New robes in a dream can mark an identity you're ready to step into — or one you fear is only costume." },
{ z:"船", e:"Boat", p:"chuán", c:"objects", o:"ji", k:"boat ship sail 船 vessel voyage",
  cls:"梦乘舟顺水，主诸事亨通，得贵人载；舟破漏水，主谋事有阻。",
  rd:"To ride a boat with the current foretells all matters flowing and a patron carrying you; a leaking hull warns of a venture obstructed.",
  md:"The boat is what carries you across feeling you can't cross on foot. Ask whether the vessel you're trusting is sound — and who is steering." },
{ z:"灯", e:"Lamp", p:"dēng", c:"objects", o:"ji", k:"lamp light candle 灯火 lantern flame",
  cls:"梦见灯火通明，主前途光明，心事得解；灯灭，主运气暂晦。",
  rd:"A lamp burning bright foretells a clear road ahead and a worry resolved; a lamp gone out means fortune dimming for a while.",
  md:"A single lamp is enough to walk by. The dream may be pointing out how little light you actually need to take the next step." },
{ z:"书", e:"A Book", p:"shū", c:"objects", o:"ji", k:"book read scroll 书本 study writing",
  cls:"梦见开卷诵读，主学业精进，功名有望；得奇书，主贵人指点。",
  rd:"To open a book and read aloud foretells learning deepening and honours within reach; to be given a rare book means a mentor's guidance coming.",
  md:"The book in a dream is knowledge you already hold, filed somewhere you can't reach awake. Notice which page it fell open to." },
{ z:"锁", e:"A Lock", p:"suǒ", c:"objects", o:"ping", k:"lock key 锁 door shut open",
  cls:"梦见开锁而通，主困局得解，前路豁然；锁而不开，主心事未了。",
  rd:"A lock that turns and opens foretells a deadlock broken and the road ahead suddenly clear; one that won't open means a matter still unfinished in the heart.",
  md:"Every lock in a dream implies a key you haven't found yet. What have you decided is closed to you that might only be waiting for the right turn?" },
{ z:"针", e:"A Needle", p:"zhēn", c:"objects", o:"ping", k:"needle thread sew 针线 mend prick",
  cls:"梦见穿针引线，主姻缘可成，事得连缀；针刺其身，主微忧扰心。",
  rd:"To thread a needle foretells a match that can be made and matters that come together; a needle's prick warns of a small worry nagging.",
  md:"The needle mends and it wounds with the same point. The dream may be about a repair that can't be made without a little pain first." },
{ z:"伞", e:"Umbrella", p:"sǎn", c:"objects", o:"ji", k:"umbrella parasol 雨伞 shelter",
  cls:"梦见张伞遮雨，主得庇护，逢凶化吉。",
  rd:"To raise an umbrella against the rain foretells shelter found, and ill fortune turned aside.",
  md:"The umbrella is protection you carry and unfold only when needed. Who or what is your shelter — and are you letting yourself stand under it?" },

/* ============================ 建筑 BUILDINGS ============================ */
{ z:"房屋", e:"House", p:"fáng wū", c:"buildings", o:"ji", s:1, k:"house home building 房子 room dwelling",
  cls:"梦见华屋高堂，主家业昌隆；屋宇修葺，主运势更新。",
  rd:"A fine, high-halled house foretells a flourishing estate; a house being repaired means fortune renewing itself.",
  md:"The house in a dream is very often the self. Which rooms did you visit — and which doors did you not open?" },
{ z:"门", e:"Gate · Door", p:"mén", c:"buildings", o:"ji", k:"gate door 门 entrance threshold",
  cls:"梦见大门洞开，主机遇将至，宾客盈门；门闭不开，主时机未到。",
  rd:"A great gate standing open foretells opportunity coming and guests filling the doorway; a shut gate means the moment has not yet arrived.",
  md:"A door is a decision with hinges. The dream may be showing you a threshold you keep approaching and not crossing." },
{ z:"桥", e:"Bridge", p:"qiáo", c:"buildings", o:"ji", k:"bridge cross 桥 span river",
  cls:"梦过长桥而安，主转折得渡，前程可期；桥断，主中道有阻。",
  rd:"To cross a long bridge safely foretells a turning point survived and a hopeful road; a broken bridge warns of an obstacle midway.",
  md:"A bridge is faith you can walk on. The dream may be measuring how much you trust the span between where you are and where you mean to be." },
{ z:"墙", e:"Wall", p:"qiáng", c:"buildings", o:"ping", k:"wall barrier 墙 climb obstacle",
  cls:"梦见高墙拦路，主暂遇阻隔；越墙而过，主排除万难。",
  rd:"A high wall blocking the road warns of an obstruction for now; to climb over it means every difficulty overcome.",
  md:"The wall is the limit you keep meeting. In a dream it can be worth asking whether it's holding something out — or you in." },
{ z:"塔", e:"Pagoda · Tower", p:"tǎ", c:"buildings", o:"ji", k:"tower pagoda 塔 high tall",
  cls:"梦登宝塔，主步步高升，功德圆满。",
  rd:"To climb a treasure-pagoda foretells a rise by measured steps, and a work brought to its full merit.",
  md:"The tower lifts you above your own vantage. The dream may be offering a longer view of a life you've only been seeing from the ground." },
{ z:"井", e:"A Well", p:"jǐng", c:"buildings", o:"ji", k:"well water deep 水井 spring",
  cls:"梦见井水清满，主财源不竭，家道润泽；井枯，主根本渐亏。",
  rd:"A well brimming with clear water foretells an inexhaustible source and a well-watered house; a dry well warns of a source running down.",
  md:"The well draws on what lies too deep to see. The dream may be asking whether you're still feeding the source you keep drawing from." },
{ z:"庙", e:"A Temple", p:"miào", c:"buildings", o:"ji", k:"temple shrine 寺庙 pray sacred",
  cls:"梦入庙宇焚香，主神明护佑，所求可应。",
  rd:"To enter a temple and offer incense foretells the gods' protection, and a petition that may be answered.",
  md:"The temple in a dream is where you go to speak to what is larger than you. Whatever you knelt before, it's the shape of your own reverence." },
{ z:"坟墓", e:"A Grave · Tomb", p:"fén mù", c:"buildings", o:"ji", k:"grave tomb 坟 burial mound",
  cls:"梦见坟墓高大，反主家道兴旺，祖荫庇身；扫墓祭拜，主福泽绵延。",
  rd:"A large, well-kept grave, contrary to dread, foretells a thriving house and the ancestors' shelter; tending a tomb foretells blessing that runs on.",
  md:"The tomb in a dream honours what has ended without erasing it. It may be asking you to keep a grief well-tended rather than buried and forgotten." },
{ z:"楼梯", e:"Stairs", p:"lóu tī", c:"buildings", o:"ji", k:"stairs steps climb 台阶 ascend",
  cls:"梦见拾级而上，主循序渐进，步步登高；下楼，主宜守成谦退。",
  rd:"To go up a staircase step by step foretells orderly progress and a steady climb; to descend counsels holding what you have and yielding gracefully.",
  md:"Stairs make the impossible height into a series of possible steps. The dream may be reminding you the whole ascent was never the ask — only the next tread." },
{ z:"迷宫", e:"A Maze", p:"mí gōng", c:"buildings", o:"xiong", k:"maze labyrinth lost 迷宫 corridor",
  cls:"梦入迷途回环，主心有困惑，宜静定寻路。",
  rd:"To wander a winding maze foretells a mind in confusion — be still, and the way will show itself.",
  md:"The maze dream tends to arrive when you're overthinking a decision with a simple answer. The exit is usually behind you, not deeper in." },

/* ============================ 生死 LIFE & DEATH ============================ */
{ z:"死", e:"Death", p:"sǐ", c:"lifedeath", o:"ji", s:1, k:"death die dead 死亡 dying end",
  cls:"梦见己死复生，主脱胎换骨，否极泰来；见人死，主除旧布新。",
  rd:"To dream you die and live again foretells a self remade and the worst turned to best; to see another die foretells the old cleared for the new.",
  md:"Death in a dream almost never predicts a death. It marks an ending your waking self hasn't finished mourning — a role, a season, a version of you outgrown." },
{ z:"结婚", e:"A Wedding", p:"jié hūn", c:"lifedeath", o:"ji", s:1, k:"wedding marriage bride 婚礼 marry",
  cls:"梦见婚嫁之喜，主诸事和合，然亦有反象，主离别之兆。",
  rd:"To dream of a wedding foretells matters joining in harmony — yet the old book warns of the mirror-omen, a parting hiding inside the celebration.",
  md:"A wedding in a dream is a union of two parts of a life. The pageantry may matter less than who was standing beside you, and how you felt when you turned to look." },
{ z:"生育", e:"Giving Birth", p:"shēng yù", c:"lifedeath", o:"ji", k:"birth born baby 生子 delivery",
  cls:"梦见产子顺利，主新事初成，喜庆临门。",
  rd:"To give birth easily foretells a new thing brought into being, and celebration at the door.",
  md:"The birth dream delivers whatever you've been carrying — a project, a self, a decision made in the dark. The labour was real even if the child is a metaphor." },
{ z:"葬礼", e:"A Funeral", p:"zàng lǐ", c:"lifedeath", o:"ji", k:"funeral burial mourn 葬礼 wake",
  cls:"梦见送葬之仪，主旧事得终，卸却重负。",
  rd:"To attend a funeral in a dream foretells an old matter properly ended, and a heavy load set down.",
  md:"The funeral gives grief its ceremony. The dream may be granting you the goodbye you never got to say out loud." },
{ z:"重逢", e:"A Reunion", p:"chóng féng", c:"lifedeath", o:"ji", k:"reunion meet again 重逢 return",
  cls:"梦见故人重逢，主久别得聚，缘分未尽。",
  rd:"To meet a loved one again after long parting foretells a coming-together, a bond not yet spent.",
  md:"Whoever you were reunited with in sleep, the dream chose them for a reason. What did being near them again restore in you?" },
{ z:"祖先", e:"Ancestors", p:"zǔ xiān", c:"lifedeath", o:"ji", k:"ancestor forebear 祖先 grandparent dead",
  cls:"梦见祖先入梦嘱咐，主家有护佑，宜谨遵祖训。",
  rd:"An ancestor entering the dream with counsel foretells the family's protection — heed the old instruction.",
  md:"The dead who visit us carrying advice are often carrying our own deepest values, worn familiar enough to finally trust. Listen for what they told you." },
{ z:"病愈", e:"Recovery", p:"bìng yù", c:"lifedeath", o:"ji", k:"healing recover well 康复 better cure",
  cls:"梦见病体渐愈，主时来运转，忧散福生。",
  rd:"To dream of recovering from illness foretells fortune turning, worry scattering, blessing setting in.",
  md:"The recovery dream tends to come right as the hardest part is passing. Your sleeping mind often knows you've turned the corner before you do." },

/* ============================ 鬼神 SPIRITS & GODS ============================ */
{ z:"鬼", e:"A Ghost", p:"guǐ", c:"spirits", o:"ping", s:1, k:"ghost spirit haunt 鬼魂 phantom",
  cls:"梦见遇鬼而不惧，反主消灾解厄；与鬼语，主得旧人相助。",
  rd:"To meet a ghost and feel no fear, contrary to dread, foretells calamity dispelled; to speak with one means help from someone long gone.",
  md:"The ghost is what refuses to be finished with — a guilt, a loss, a person unmourned. The dream is not haunting you; it's asking you to turn and face the thing at last." },
{ z:"神仙", e:"An Immortal", p:"shén xiān", c:"spirits", o:"ji", k:"immortal deity god 神仙 sage divine",
  cls:"梦见神仙降临指引，主贵人相助，疑难顿解。",
  rd:"An immortal descending to guide you foretells a powerful helper, and a hard knot suddenly loosed.",
  md:"The divine figure in a dream speaks with an authority you don't dare claim awake. Whatever it told you, some deep part of you already believes it." },
{ z:"佛", e:"The Buddha", p:"fó", c:"spirits", o:"ji", k:"buddha bodhisattva 佛 enlighten mercy",
  cls:"梦见佛像放光，主心念澄明，灾厄尽消。",
  rd:"To dream of the Buddha shining foretells a mind gone clear and every misfortune melting away.",
  md:"The image of perfect calm arrives in dreams for the restless. It may be showing you the stillness you're capable of, if you stopped grasping for a moment." },
{ z:"财神", e:"God of Wealth", p:"cái shén", c:"spirits", o:"ji", k:"wealth god fortune 财神 money luck",
  cls:"梦见财神临门，主财运亨通，求财必得。",
  rd:"The God of Wealth appearing at your door foretells fortune flowing and money sought and found.",
  md:"Prosperity in a dream wears a friendly face when you feel you deserve it. Notice whether you welcomed him in — or felt you had to earn the visit." },
{ z:"龙王", e:"Dragon King", p:"lóng wáng", c:"spirits", o:"ji", k:"dragon king sea 龙王 rain water lord",
  cls:"梦见龙王现身，主大权可掌，风雨得调。",
  rd:"The Dragon King revealing himself foretells great authority to be held, and the storms of your life brought into order.",
  md:"The lord of water and weather rules exactly what you can't control. The dream may be about making peace with a force in your life far larger than your will." },
{ z:"祭祀", e:"Making an Offering", p:"jì sì", c:"spirits", o:"ji", k:"offering ritual sacrifice 祭祀 incense worship",
  cls:"梦见虔诚祭祀，主诚感神明，所愿得遂。",
  rd:"To make a devout offering foretells sincerity that moves the unseen, and a wish carried through.",
  md:"The offering dream is about what you're willing to give up for what you want. What did you lay down — and did it feel like loss or like relief?" },
{ z:"神像", e:"A Divine Statue", p:"shén xiàng", c:"spirits", o:"ji", k:"statue idol god image 神像 shrine",
  cls:"梦见神像庄严，主敬畏在心，得神护持；神像倾倒，主信念动摇。",
  rd:"A solemn divine statue foretells reverence held and protection given; a statue toppling warns of a faith beginning to shake.",
  md:"What we put on a pedestal in dreams shows what we've made sacred. If it fell, the dream may be asking whether the thing still deserves the altar." },

/* ============================ 情感 FEELING ============================ */
{ z:"哭", e:"Weeping", p:"kū", c:"emotions", o:"ji", s:1, k:"cry weep sob 哭泣 tears grief",
  cls:"梦中大哭一场，反主喜庆将至，忧结尽舒。",
  rd:"To weep hard in a dream, against all fear, foretells a coming joy and a knotted grief fully loosed.",
  md:"The book calls weeping a good omen, and the body agrees — tears are release, not ruin. Whatever you cried for in sleep had been waiting a long time to be felt." },
{ z:"笑", e:"Laughter", p:"xiào", c:"emotions", o:"ping", k:"laugh smile joy 笑 happy",
  cls:"梦中欢笑，主心境舒畅；然大笑无端，反主乐极生忧。",
  rd:"Laughter in a dream foretells an easy heart; yet wild laughter without cause warns that joy pushed too far turns back to sorrow.",
  md:"Laughter in a dream is honest in a way waking laughter isn't. Ask whether it was delight — or the kind we use to keep something else at bay." },
{ z:"恐惧", e:"Fear", p:"kǒng jù", c:"emotions", o:"ping", k:"fear afraid terror 恐惧 scared dread",
  cls:"梦中惊惧难安，主心有挂碍，宜寻其根而解。",
  rd:"To feel gripped by fear in a dream means a care lodged in the heart — find its root, and it lets go.",
  md:"Fear in a dream is rarely about the thing chasing you. It's the feeling itself, finally given a shape you can look at. Ask what it's actually the size of." },
{ z:"喜悦", e:"Joy", p:"xǐ yuè", c:"emotions", o:"ji", k:"joy happy delight 喜悦 gladness bliss",
  cls:"梦中欢喜盈怀，主好事将成，福气盈门。",
  rd:"A heart brimming with gladness in a dream foretells a good thing completing itself and blessing filling the house.",
  md:"Unearned joy in a dream is worth trusting. Your sleeping mind doesn't flatter you — if it gave you that lightness, some part of you knows it's coming." },
{ z:"相思", e:"Longing", p:"xiāng sī", c:"emotions", o:"ping", k:"longing yearn miss 相思 pine love",
  cls:"梦中思念成疾，主情深难舍，或有远信可期。",
  rd:"To ache with longing in a dream foretells a love hard to release — and perhaps word from far away.",
  md:"Longing in a dream names who or what you've been missing without permission to admit it awake. The absence you woke reaching for is telling you something." },
{ z:"怒", e:"Anger", p:"nù", c:"emotions", o:"xiong", k:"anger rage furious 愤怒 mad wrath",
  cls:"梦中盛怒难平，主积郁待发，宜疏勿堵。",
  rd:"Anger that won't cool in a dream means something long swallowed is waiting to come out — let it flow rather than dam it.",
  md:"The anger you feel in sleep is often the anger you've refused all day. It isn't a flaw in the dream; it's a message about a boundary you've let be crossed." },
{ z:"羞愧", e:"Shame", p:"xiū kuì", c:"emotions", o:"ping", k:"shame embarrass naked 羞愧 exposed",
  cls:"梦中蒙羞难堪，主自省将至，改过更新。",
  rd:"To feel shame in a dream foretells a reckoning with yourself and a turning toward change.",
  md:"The dream of being exposed or ashamed is one of the most human there is. It usually points not to a real failing but to a fear of being seen as less than you pretend." },
{ z:"安宁", e:"Peace", p:"ān níng", c:"emotions", o:"ji", k:"peace calm serene 安宁 quiet still",
  cls:"梦中心境安然，主诸事和顺，福寿康宁。",
  rd:"A settled, peaceful heart in a dream foretells matters running smooth, and a life of quiet, healthful length.",
  md:"When peace arrives unbidden in a dream, it's worth asking what your waking life would have to become to keep it. The dream has shown you it's possible." },

/* ============================ 行为 ACTIONS ============================ */
{ z:"飞", e:"Flying", p:"fēi", c:"actions", o:"ji", s:1, k:"fly flying soar 飞行 float air rise",
  cls:"梦见腾空飞行，主志得意满，超脱困境，青云直上。",
  rd:"To fly up into the open air foretells ambition fulfilled, troubles left below, and a straight rise into the blue.",
  md:"The flying dream is freedom the body can't otherwise have. It tends to visit when you've either just slipped a constraint — or badly need to. How high you dared says a lot." },
{ z:"坠落", e:"Falling", p:"zhuì luò", c:"actions", o:"xiong", s:1, k:"fall falling drop 坠落 cliff plunge",
  cls:"梦见自高坠落，主根基未稳，心有失据，宜守勿进。",
  rd:"To fall from a height warns that a footing is not yet firm and something feels out of your control — hold, don't advance.",
  md:"The falling dream and its jolt awake are almost universal. It usually surfaces when you've lost your grip on something — a plan, a certainty — and haven't admitted it yet." },
{ z:"被追", e:"Being Chased", p:"bèi zhuī", c:"actions", o:"xiong", s:1, k:"chased pursued run 被追 flee escape",
  cls:"梦见被人追逐，主有事逼身，心存逃避，宜正面而对。",
  rd:"To be chased in a dream means a matter is pressing close that you'd rather flee — turn and face it, and the pursuit ends.",
  md:"Whatever chases you in a dream is nearly always something in yourself you've been outrunning. The old advice holds: in the dream, and awake, the moment you stop and turn, it usually changes shape." },
{ z:"掉牙", e:"Losing Teeth", p:"diào yá", c:"actions", o:"ping", s:1, k:"teeth tooth fall out 掉牙 losing teeth",
  cls:"梦见牙齿脱落，古谓主家中长辈之忧，亦主旧事更替、脱故迎新。",
  rd:"To dream your teeth fall out — the old book reads it as concern for an elder of the house, and also as the shedding of the old to make way for the new.",
  md:"The most asked-about dream of all. Modern readings tie it to change, control, and how we're seen — teeth are how we bite down and how we smile. Ask what you're afraid of losing your grip on, or your face over." },
{ z:"游泳", e:"Swimming", p:"yóu yǒng", c:"actions", o:"ji", k:"swim water 游泳 dive float",
  cls:"梦见游泳渡水，主克服艰难，得力自渡。",
  rd:"To swim across water foretells hardship overcome by your own effort, and a crossing made under your own power.",
  md:"To swim is to stay afloat in feeling rather than drown in it or flee it. The dream may be showing you that you already know how to move through this." },
{ z:"迷路", e:"Getting Lost", p:"mí lù", c:"actions", o:"ping", k:"lost way path 迷路 wander direction",
  cls:"梦见迷失道路，主心无定向，宜静思本心而后行。",
  rd:"To lose your way in a dream means a heart without a fixed direction — sit with what you truly want, then move.",
  md:"The lost dream isn't about geography. It's the mind admitting it doesn't know which way it wants to go. That admission, uncomfortable as it is, is the beginning of the answer." },
{ z:"考试", e:"Taking an Exam", p:"kǎo shì", c:"actions", o:"ping", k:"exam test school 考试 unprepared fail",
  cls:"梦见临考慌张，主心怀忧惧，恐力有不逮，宜安神自信。",
  rd:"To face an exam in a panic foretells a heart full of dread that you may fall short — steady yourself; you know more than you fear.",
  md:"The exam dream, long after school is over, is pure performance anxiety in costume. It surfaces when you feel measured and unready. Usually you're more prepared than the dream insists." },
{ z:"追逐", e:"Chasing Something", p:"zhuī zhú", c:"actions", o:"ping", k:"chase pursue catch 追逐 reach",
  cls:"梦见奋力追逐，主有志所求，然求之过急，反致失得。",
  rd:"To chase hard after something foretells a real desire — but pursued too fiercely, the grasping itself may lose it.",
  md:"When you're the one chasing in a dream, ask what you're pursuing awake, and whether it's running because you want it too tightly. Some things arrive only when you slow down." },
{ z:"跌倒", e:"Stumbling", p:"diē dǎo", c:"actions", o:"ping", k:"trip fall stumble 跌倒 slip",
  cls:"梦见途中跌倒，主行事有失，然跌而复起，主终能振作。",
  rd:"To stumble on the road foretells a misstep in your affairs — yet to fall and rise again means you'll recover your feet.",
  md:"The stumble dream isn't a warning of disaster; it's often about the fear of it. What matters is that in the dream, as awake, getting up is available." },
{ z:"沐浴", e:"Bathing", p:"mù yù", c:"actions", o:"ji", k:"bath wash clean 沐浴 bathe purify",
  cls:"梦见沐浴净身，主洗去尘秽，除病消灾。",
  rd:"To bathe and cleanse yourself foretells old grime washed away, sickness and misfortune both lifted.",
  md:"The bathing dream is the psyche wanting to be clean of something. What have you been carrying that you're ready to rinse off?" },
{ z:"歌舞", e:"Singing & Dancing", p:"gē wǔ", c:"actions", o:"ji", k:"sing dance music 歌舞 celebrate",
  cls:"梦见歌舞欢腾，主喜事将临，家宅和乐。",
  rd:"To sing and dance in a dream foretells a joy approaching and a household at ease with itself.",
  md:"To dance in a dream is the body agreeing with your life for once. It tends to come when some tension you've held is finally, quietly, resolving." },
{ z:"读书", e:"Studying", p:"dú shū", c:"actions", o:"ji", k:"study read learn 读书 school knowledge",
  cls:"梦见勤学不辍，主学问日增，功名有望。",
  rd:"To study without pause in a dream foretells learning that mounts by the day, and honours within reach.",
  md:"The study dream honours a hunger you may not be feeding awake. What have you been meaning to learn that keeps surfacing in sleep?" },
{ z:"寻物", e:"Searching for Something Lost", p:"xún wù", c:"actions", o:"ping", k:"search find lost 寻找 seek missing",
  cls:"梦见遍寻失物，主心有所缺，寻而复得，主失而复来。",
  rd:"To search everywhere for a lost thing means a lack felt in the heart; to find it means what was lost returning.",
  md:"The thing you hunt for in a dream is rarely the thing. It's a quality — a safety, a self, a person — you've mislaid. Notice what you were looking under." },

/* ---- second gathering ---- */
{ z:"鹿", e:"Deer", p:"lù", c:"animals", o:"ji", k:"deer stag 鹿 antler fortune",
  cls:"梦见鹿入林苑，主得禄位，官运亨通。",
  rd:"A deer entering the grove foretells rank and salary — 鹿 shares the sound of 禄 — and an official road running smooth.",
  md:"The deer is fortune that startles easily. The dream may be asking you to move gently toward a good thing so as not to spook it." },
{ z:"象", e:"Elephant", p:"xiàng", c:"animals", o:"ji", k:"elephant 大象 tusk strong",
  cls:"梦见白象现身，主福德深厚，逢难自解。",
  rd:"A white elephant appearing foretells deep-rooted blessing, and troubles that untangle on their own.",
  md:"The elephant carries great weight without hurry. It visits dreamers who've been treating their strength as a burden rather than a gift." },
{ z:"狮", e:"Lion", p:"shī", c:"animals", o:"ping", k:"lion 狮子 roar king beast",
  cls:"梦见雄狮当道，主威名可立，然须防刚极招损。",
  rd:"A lion astride the road foretells a name built on strength — but guard against a fierceness so hard it wounds you.",
  md:"The lion is dignity that can curdle into pride. Ask whether the roar in you is protecting your ground or just demanding to be feared." },
{ z:"鹰", e:"Eagle", p:"yīng", c:"animals", o:"ji", k:"eagle hawk 老鹰 soar prey",
  cls:"梦见鹰击长空，主志向远大，一举成名。",
  rd:"An eagle striking through the high sky foretells a far-reaching ambition and a single act that makes your name.",
  md:"The eagle sees the whole field and strikes once. The dream may be counseling patience — the long circle before the decisive dive." },
{ z:"鸳鸯", e:"Mandarin Ducks", p:"yuān yang", c:"animals", o:"ji", k:"mandarin ducks pair 鸳鸯 love couple",
  cls:"梦见鸳鸯戏水，主夫妻和睦，姻缘美满。",
  rd:"Mandarin ducks playing on the water foretell a harmonious marriage and a love that keeps its pair.",
  md:"The paired ducks are devotion made visible. The dream may be measuring the state of a partnership — or a longing for one that matches." },
{ z:"蛙", e:"Frog", p:"wā", c:"animals", o:"ji", k:"frog toad 青蛙 pond rain",
  cls:"梦见群蛙齐鸣，主雨水调和，年岁丰稔。",
  rd:"A chorus of frogs foretells rains in good measure and a fat, well-fed year.",
  md:"The frog lives between water and land, at ease in both. The dream may be about a change of element you're more ready for than you think." },
{ z:"蚕", e:"Silkworm", p:"cán", c:"animals", o:"ji", k:"silkworm cocoon 蚕 silk thread",
  cls:"梦见蚕食桑吐丝，主勤劳有成，积渐得利。",
  rd:"A silkworm feeding and spinning foretells diligence rewarded and profit gathered thread by thread.",
  md:"The silkworm turns plain leaves into something luminous, entirely by patience. The dream may be honouring slow, unglamorous work of yours that's becoming beautiful." },
{ z:"兰", e:"Orchid", p:"lán", c:"plants", o:"ji", k:"orchid 兰花 fragrance noble",
  cls:"梦见幽兰吐芳，主德行高洁，得良友相知。",
  rd:"A hidden orchid giving off its scent foretells a clean, high character and a true friend who understands you.",
  md:"The orchid perfumes the empty valley whether or not anyone comes. The dream may be reminding you that some worth doesn't need an audience." },
{ z:"菊", e:"Chrysanthemum", p:"jú", c:"plants", o:"ji", k:"chrysanthemum 菊花 autumn recluse",
  cls:"梦见秋菊盛开，主晚景安泰，清福可享。",
  rd:"Chrysanthemums in full autumn bloom foretell a peaceful later season and a quiet blessing to enjoy.",
  md:"The chrysanthemum blooms when the year is letting go. It tends to visit dreamers who need reassurance that late is not the same as too late." },
{ z:"葡萄", e:"Grapes", p:"pú tao", c:"plants", o:"ji", k:"grape vine 葡萄 cluster fruit",
  cls:"梦见葡萄满架，主子孙众多，家业繁盛。",
  rd:"Grapes hanging thick on the trellis foretell many descendants and a family widening into plenty.",
  md:"The vine gives its fruit in clusters, never singly. The dream may be about an abundance that comes all at once, or not at all." },
{ z:"荆棘", e:"Thorns", p:"jīng jí", c:"plants", o:"xiong", k:"thorn briar 荆棘 obstacle prick",
  cls:"梦见荆棘塞途，主前有阻碍，须耐心开路。",
  rd:"Thorns choking the path warn of obstacles ahead — clear the way patiently, and don't force through.",
  md:"The thorn dream marks a difficulty you can't just push past. What in your road needs cutting back slowly rather than charging at?" },
{ z:"老人", e:"An Old Person", p:"lǎo rén", c:"people", o:"ji", k:"elder old wise 老人 aged grandparent",
  cls:"梦见白发老者相告，主得良言指引，逢难得助。",
  rd:"A white-haired elder giving you word foretells good counsel and help when the road turns hard.",
  md:"The old one in a dream carries the part of you that has already lived through this. What did the wiser, later version of you come back to say?" },
{ z:"官吏", e:"An Official", p:"guān lì", c:"people", o:"ji", k:"official magistrate 官吏 power office",
  cls:"梦见官吏和颜相待，主谋事得准，事有所成。",
  rd:"An official receiving you kindly foretells a petition approved and a matter carried through.",
  md:"The figure of officialdom in a dream is your relationship to permission and rules. Were they an ally, or one more gate to get past?" },
{ z:"军人", e:"A Soldier", p:"jūn rén", c:"people", o:"ping", k:"soldier warrior army 军人 guard",
  cls:"梦见军人列阵，主纪律当严，防有争斗之事。",
  rd:"Soldiers drawn up in ranks counsel discipline, and warn that a conflict may be near.",
  md:"The soldier is the part of you that stands guard. The dream may be asking what you're defending — and whether it still needs an armed watch." },
{ z:"雾", e:"Fog · Mist", p:"wù", c:"nature", o:"ping", k:"fog mist haze 雾气 unclear",
  cls:"梦见云雾迷蒙，主前路不明，宜守静待时。",
  rd:"Fog closing in foretells a road you can't yet see — stay still and wait for it to lift.",
  md:"The fog dream isn't a warning of danger, only of not-knowing. It often comes when you're pushing for clarity that simply hasn't arrived. Let it burn off." },
{ z:"洪水", e:"Flood", p:"hóng shuǐ", c:"nature", o:"xiong", k:"flood deluge water 洪水 overflow drown",
  cls:"梦见洪水滔天，主情势难控，宜早避而后图。",
  rd:"A flood rising to the sky warns of a situation past controlling — get to high ground first, and plan after.",
  md:"When water overwhelms in a dream, feeling has outrun your capacity to hold it. The dream isn't asking you to dam the flood, only to stop standing in it." },
{ z:"地震", e:"Earthquake", p:"dì zhèn", c:"nature", o:"ping", k:"earthquake quake shake 地震 tremor",
  cls:"梦见地动山摇，主根本有变，宜稳心以待。",
  rd:"The ground heaving and the hills shaking foretell a change at the foundation — steady your heart and wait it out.",
  md:"The earthquake dream shakes what you'd assumed was solid — a belief, a home, a certainty. It rarely predicts disaster; it names a foundation already moving." },
{ z:"泉", e:"A Spring", p:"quán", c:"nature", o:"ji", k:"spring water source 泉水 fountain fresh",
  cls:"梦见清泉涌出，主生机再起，财源新开。",
  rd:"A clear spring welling up foretells fresh vitality and a new source of income opening.",
  md:"The spring rises from a depth you didn't dig. The dream may be pointing to a renewal already surfacing in you, from somewhere older than effort." },
{ z:"面", e:"The Face", p:"miàn", c:"body", o:"ping", k:"face visage mask 面容 mirror",
  cls:"梦见己面光洁，主气色转佳，运程向好；面污，主须防羞辱。",
  rd:"To see your own face clean and bright foretells fortune brightening; a soiled face warns to guard against humiliation.",
  md:"The face in a dream is the self you show. Whatever state it was in, the dream is commenting on the gap between how you feel and how you appear." },
{ z:"舌", e:"The Tongue", p:"shé", c:"body", o:"ping", k:"tongue speech 舌头 speak taste",
  cls:"梦见舌利能言，主口才得用；舌伤难语，主言多招祸。",
  rd:"A ready, able tongue foretells eloquence put to use; a hurt tongue that can't speak warns that too many words bring trouble.",
  md:"The tongue is where thought becomes consequence. The dream may be weighing something you've said — or badly need to." },
{ z:"足", e:"The Feet", p:"zú", c:"body", o:"ji", k:"feet foot walk 脚 step ground",
  cls:"梦见双足稳健，主行止得宜，出行平安。",
  rd:"Two steady feet foretell sound judgment in coming and going, and safe travels.",
  md:"The feet are your relationship to the ground and to leaving. If they were bound or bare or wounded, the dream is asking about your freedom to move." },
{ z:"胡须", e:"A Beard", p:"hú xū", c:"body", o:"ji", k:"beard whiskers 胡须 mustache elder",
  cls:"梦见须发丰美，主威仪日盛，寿禄双全。",
  rd:"A full, handsome beard foretells growing dignity, and both long life and good fortune.",
  md:"The beard is age worn as authority. The dream may be about stepping into a gravitas you've been too young — or too unsure — to claim." },
{ z:"珠宝", e:"Jewels", p:"zhū bǎo", c:"objects", o:"ji", k:"jewel gem treasure 珠宝 pearl jade precious",
  cls:"梦见珠宝盈匣，主贵气临身，得意外之财。",
  rd:"A casket brimming with jewels foretells honour drawing near and wealth arriving unlooked-for.",
  md:"Jewels in a dream are worth made small and portable. The dream may be showing you a value in yourself you've been keeping locked away." },
{ z:"笔", e:"A Writing Brush", p:"bǐ", c:"objects", o:"ji", k:"brush pen write 毛笔 ink calligraphy",
  cls:"梦见得笔挥毫，主文思泉涌，功名有兆。",
  rd:"To take up the brush and write foretells thoughts flowing like a spring, and a sign of honours to come.",
  md:"The brush is your power to author your own account. The dream may be nudging you to write the thing — the letter, the plan, the life — you keep composing only in your head." },
{ z:"钟", e:"A Bell", p:"zhōng", c:"objects", o:"ji", k:"bell chime 钟声 ring toll temple",
  cls:"梦见钟声远扬，主声名远播，喜讯将至。",
  rd:"A bell's sound carrying far foretells a name that travels and good news on its way.",
  md:"The bell marks the hour whether or not you're listening. The dream may be a summons — to attention, to a threshold, to something it's finally time for." },
{ z:"城", e:"A City Wall", p:"chéng", c:"buildings", o:"ji", k:"city wall fortress 城墙 rampart",
  cls:"梦见登城远眺，主胸怀壮阔，前程可观。",
  rd:"To climb the city wall and gaze far foretells a broad ambition and a promising road.",
  md:"The wall both defends and confines. From atop it in a dream, ask whether you're surveying your kingdom or pacing the edge of your limits." },
{ z:"宫殿", e:"A Palace", p:"gōng diàn", c:"buildings", o:"ji", k:"palace hall 宫殿 throne grand",
  cls:"梦入宫殿华美，主贵人相引，荣显可期。",
  rd:"To enter a splendid palace foretells a powerful guide leading you, and honours worth expecting.",
  md:"The palace is grandeur you're allowed to walk through but may not feel you belong in. The dream may be asking whether you'd let yourself take a seat." },
{ z:"厕所", e:"A Latrine", p:"cè suǒ", c:"buildings", o:"ji", k:"toilet latrine 厕所 privy relief",
  cls:"梦见入厕如意，反主得财去秽，郁结得舒。",
  rd:"To relieve yourself with ease in a dream, oddly, foretells wealth gained, filth cleared, and a knot in the chest loosened.",
  md:"The dream of needing, and finding, relief is the psyche asking to let go of what it's been holding. Sometimes it's that literal — and that necessary." },
{ z:"观音", e:"Guanyin", p:"guān yīn", c:"spirits", o:"ji", k:"guanyin bodhisattva mercy 观音 compassion",
  cls:"梦见观音显圣，主慈悲护佑，苦厄得离。",
  rd:"Guanyin appearing in radiance foretells the shelter of mercy, and a hardship you'll be delivered from.",
  md:"The figure of compassion arrives in dreams for those being hard on themselves. Whatever she offered, it's the gentleness you've been withholding from your own life." },
{ z:"土地", e:"The Earth God", p:"tǔ dì", c:"spirits", o:"ji", k:"earth god local 土地公 land protector",
  cls:"梦见土地神来护，主家宅平安，根基得守。",
  rd:"The local Earth God coming to guard you foretells a peaceful household and a foundation kept safe.",
  md:"The humblest of the gods watches over one small patch of ground. The dream may be honouring the modest, local loyalties that actually hold your life together." },
{ z:"妖", e:"A Demon", p:"yāo", c:"spirits", o:"ping", k:"demon monster fiend 妖怪 evil",
  cls:"梦见降伏妖邪，主克除心魔，转祸为福。",
  rd:"To subdue a demon in a dream foretells an inner devil mastered and misfortune turned to blessing.",
  md:"The monster in the dream is almost always a disowned part of yourself in frightening dress. What you defeat by facing it, you get to take back." },
{ z:"惊", e:"Shock", p:"jīng", c:"emotions", o:"ping", k:"shock startle fright 惊吓 sudden",
  cls:"梦中骤惊而醒，主有事出意外，宜预为之防。",
  rd:"To be startled awake in a dream foretells the unexpected — prepare, so it finds you ready.",
  md:"The jolt of shock in a dream often marks something your waking mind has half-noticed and not yet let itself react to. What surprised you that maybe shouldn't have?" },
{ z:"孤独", e:"Loneliness", p:"gū dú", c:"emotions", o:"ping", k:"lonely alone solitude 孤独 isolated",
  cls:"梦中形单影只，主心有所思，宜自省而后近人。",
  rd:"To stand alone with only your shadow foretells a heart deep in thought — know yourself first, then come near others.",
  md:"The loneliness of a dream can be the truest reading of a room full of people. It may be asking who you're actually connected to, and who you only stand beside." },
{ z:"争吵", e:"A Quarrel", p:"zhēng chǎo", c:"actions", o:"ji", k:"quarrel argue fight 争吵 dispute conflict",
  cls:"梦见与人争吵，反主消解旧怨，和气将回。",
  rd:"To quarrel in a dream, against expectation, foretells an old grievance clearing and goodwill returning.",
  md:"The dream fight often airs what politeness has kept swallowed. Notice who you argued with — the dream may be handing you a conversation you've been avoiding." },
{ z:"攀登", e:"Climbing", p:"pān dēng", c:"actions", o:"ji", k:"climb ascend scale 攀登 mountain effort",
  cls:"梦见奋力攀登，主发愤图强，终能登顶。",
  rd:"To climb with effort in a dream foretells striving that will, in the end, reach the top.",
  md:"The climb dream measures your relationship to the hard, upward middle of a thing. That you kept climbing at all is the omen — not whether you reached the summit before waking." }
];
