/* 求籤 · FORTUNE STICKS — the canon of 48 fortune poems.
   Original 4-line classical-style verses composed in the Guan Yin / Wong Tai Sin
   oracle tradition. No real temple's texts are reproduced. */
"use strict";
window.KAUCIM = [
 {n:1, lv:"上上", cn:["云开雾散见青天","枯木逢春花满园","守得云开终有月","一帆风顺过千山"],
  py:["yún kāi wù sàn jiàn qīng tiān","kū mù féng chūn huā mǎn yuán","shǒu dé yún kāi zhōng yǒu yuè","yī fān fēng shùn guò qiān shān"],
  en:["The clouds unclasp, the fog disperses, blue sky stands bare;","the withered tree, meeting spring, floods the garden with bloom.","Hold long enough for the clouds to part and the moon is yours;","one sail, one fair wind — a thousand mountains fall behind."],
  i:{y:"A long grey season ends; what you endured was the price of this clearing.",c:"Frozen money moves again; a return you had written off comes back.",l:"Affection thought dead puts out new leaf — answer it before spring passes.",h:"Strength floods back like sap; rest, and the body knits itself whole.",e:"The road opens on the first push; sail now, while the wind is with you."}},
 {n:2, lv:"上吉", cn:["明月当空照九州","清风送我上兰舟","前程不必频回首","自有贵人暗里酬"],
  py:["míng yuè dāng kōng zhào jiǔ zhōu","qīng fēng sòng wǒ shàng lán zhōu","qián chéng bù bì pín huí shǒu","zì yǒu guì rén àn lǐ chóu"],
  en:["The bright moon, high in the vault, lights all nine provinces;","a clean wind hands me aboard the orchid boat.","No need to keep glancing back at the road you came by —","unseen, a patron is already squaring your account."],
  i:{y:"Quiet help arrives from someone you have not thought to ask.",c:"A steady gain, not a windfall — reliable, and enough.",l:"A kind hand reaches from an unexpected quarter; let it.",h:"Sleep comes easier now; the worst of the strain is behind.",e:"A senior speaks for you when you are not in the room."}},
 {n:3, lv:"中", cn:["半岭闲云去复来","行人到此莫徘徊","时来自有通津渡","未遇休教心暗灰"],
  py:["bàn lǐng xián yún qù fù lái","xíng rén dào cǐ mò pái huái","shí lái zì yǒu tōng jīn dù","wèi yù xiū jiào xīn àn huī"],
  en:["Halfway up the ridge, idle clouds come and go and come;","traveler, having climbed this far, do not stand and waver.","When the hour turns there will be a ferry at the crossing —","until it comes, do not let the heart go grey."],
  i:{y:"Neither open nor closed — the door is simply not yet on its hinge.",c:"Hold what you have; this is a season to keep, not to spend.",l:"Timing, not feeling, is the obstacle — patience is the whole work.",h:"Nothing serious, but do not test the body's goodwill just now.",e:"The offer will come, only later than you would like; do not force it."}},
 {n:4, lv:"下", cn:["逆水行舟浪拍天","孤帆偏遇打头风","劝君且泊芦花岸","莫向狂涛更向前"],
  py:["nì shuǐ xíng zhōu làng pāi tiān","gū fān piān yù dǎ tóu fēng","quàn jūn qiě bó lú huā àn","mò xiàng kuáng tāo gèng xiàng qián"],
  en:["Poling upstream, the waves slap up at the sky;","the lone sail meets, of all winds, the one dead ahead.","Better, friend, to moor by the reed-flower bank","than push the prow one length further into the fury."],
  i:{y:"The current is against you; effort now only tires the arms.",c:"Close the purse — an outlay this month will not come back.",l:"Words spoken now land wrong; wait for calmer water.",h:"Heed small warnings before they grow teeth; rest is medicine.",e:"Do not launch the plan this season; moor it, let the storm pass."}},
 {n:5, lv:"上上", cn:["龙归沧海得逢时","一跃天门万里驰","旧日辛勤今日报","名题金榜世人知"],
  py:["lóng guī cāng hǎi dé féng shí","yī yuè tiān mén wàn lǐ chí","jiù rì xīn qín jīn rì bào","míng tí jīn bǎng shì rén zhī"],
  en:["The dragon, back in the blue sea, has found its hour;","one leap through heaven's gate and it runs ten thousand miles.","The toil of former days is repaid in this one —","your name inked on the golden roll for all to read."],
  i:{y:"A breakthrough long earned; the ceiling you pushed on finally lifts.",c:"Substantial gain arrives with your name on it — reward and honor together.",l:"You are seen fully now; a bond deepens into something public and sure.",h:"Peak vigor; put it to use, but do not squander it on excess.",e:"Promotion, prize, or passing mark — the examiners rule in your favor."}},
 {n:6, lv:"中", cn:["花开花谢自有时","何须着意苦相催","园中自有寻芳客","静待春风第一枝"],
  py:["huā kāi huā xiè zì yǒu shí","hé xū zhuó yì kǔ xiāng cuī","yuán zhōng zì yǒu xún fāng kè","jìng dài chūn fēng dì yī zhī"],
  en:["Flowers open, flowers fall, each in its own hour —","why lean on them, why press them bitterly to hurry?","There will be a guest come looking for fragrance;","wait, quietly, for the spring wind to find the first branch."],
  i:{y:"Let events ripen; forcing them only bruises the fruit.",c:"Small and seasonal — do not chase, and it will come round.",l:"The right person is looking; be findable, not frantic.",h:"Steady if you stop pushing; the body wants rhythm, not sprint.",e:"Recognition is coming, but not on your schedule — do the work, wait."}},
 {n:7, lv:"上吉", cn:["枯井忽然涌甘泉","故人千里寄书还","莫嫌眼下无消息","好事从来在晚天"],
  py:["kū jǐng hū rán yǒng gān quán","gù rén qiān lǐ jì shū huán","mò xián yǎn xià wú xiāo xī","hǎo shì cóng lái zài wǎn tiān"],
  en:["The dry well, all at once, brims with sweet water;","a far friend, a thousand miles off, sends a letter home.","Do not grumble that no news reaches you today —","good things have always come toward evening."],
  i:{y:"A drought of news ends; expect word you had stopped waiting for.",c:"An old, forgotten claim pays out; check what you set aside.",l:"A distant tie warms again; a message you did not expect arrives.",h:"A stubborn ailment eases — the turn comes late in the course.",e:"Reward comes at the end of the effort, not the middle; keep at it."}},
 {n:8, lv:"下", cn:["镜里观花空有色","水中捞月枉劳神","劝君认取眼前路","莫把虚名误此身"],
  py:["jìng lǐ guān huā kōng yǒu sè","shuǐ zhōng lāo yuè wǎng láo shén","quàn jūn rèn qǔ yǎn qián lù","mò bǎ xū míng wù cǐ shēn"],
  en:["Flowers watched in a mirror — color, and nothing to hold;","the moon fished from the water wears out the spirit for naught.","Better, friend, to know the road that lies at your feet","than let a hollow name mislead your one life."],
  i:{y:"A tempting thing is an illusion — look past the shine.",c:"A 'sure' opportunity is a reflection; do not reach into the water.",l:"Someone is in love with an image, not you — or you with theirs.",h:"Chasing a false remedy wastes you; return to plain, real care.",e:"The glamorous offer is empty; the plain road at your feet is real."}},
 {n:9, lv:"上上", cn:["喜鹊枝头报好音","门迎珠履座生春","从今平步青云上","福禄绵绵及子孙"],
  py:["xǐ què zhī tóu bào hǎo yīn","mén yíng zhū lǚ zuò shēng chūn","cóng jīn píng bù qīng yún shàng","fú lù mián mián jí zǐ sūn"],
  en:["The magpie on the branch cries out its good report;","the door welcomes fine guests, and spring rises in the room.","From this day you climb the blue cloud at an even step —","fortune and rank run on, unbroken, to your children's children."],
  i:{y:"An auspicious turn that keeps giving; the good news is only the first.",c:"Prosperity that compounds — what arrives now seeds more.",l:"A joyful union, blessed by family; the door is open to celebration.",h:"Robust and warm; a house in good order keeps the body well.",e:"Smooth, rising advancement — a sure and lasting climb."}},
 {n:10, lv:"中", cn:["浓云欲雨未成霖","远近山川半晦明","且把闲身权且住","待看天意转分明"],
  py:["nóng yún yù yǔ wèi chéng lín","yuǎn jìn shān chuān bàn huì míng","qiě bǎ xián shēn quán qiě zhù","dài kàn tiān yì zhuǎn fēn míng"],
  en:["Thick cloud means to rain but has not come to downpour;","the hills, near and far, hang half in dusk, half in light.","Keep your idle self, for now, just where it is —","and watch until heaven's intention turns plain."],
  i:{y:"A decision is forming but unformed; do not read half-light as an answer.",c:"Neither loss nor gain yet — keep the ledger steady and wait.",l:"Feelings are real but unspoken on both sides; give it another moon.",h:"A watchful pause; note the symptom, do not yet act on it.",e:"The situation is undecided — premature moves misread the sky."}},
 {n:11, lv:"上吉", cn:["石中藏玉待良工","莫道无人识此中","一旦琢磨成器日","方知璞玉本非空"],
  py:["shí zhōng cáng yù dài liáng gōng","mò dào wú rén shí cǐ zhōng","yī dàn zhuó mó chéng qì rì","fāng zhī pú yù běn fēi kōng"],
  en:["Jade hides in the stone, waiting for the right hand;","do not say no one can see what lies within.","On the day the cutting and grinding make it a vessel,","you will know the rough jade was never empty at all."],
  i:{y:"Your worth is unrecognized, not absent — the right eye is coming.",c:"An undervalued asset; hold it, the market will find it.",l:"Someone sees past your rough surface — let them do the patient work.",h:"Small disciplines shape the body slowly; keep grinding.",e:"A mentor will cut and polish you into use; accept the correction."}},
 {n:12, lv:"下", cn:["好花偏遇夜来霜","美景无端半带伤","劝子且宽三寸气","留将根本待春阳"],
  py:["hǎo huā piān yù yè lái shuāng","měi jǐng wú duān bàn dài shāng","quàn zǐ qiě kuān sān cùn qì","liú jiāng gēn běn dài chūn yáng"],
  en:["The good flower, of all nights, meets the frost that comes;","the fine prospect, for no reason, is half spoiled.","I counsel you: loosen three inches of your breath,","keep the root alive, and wait for the spring sun."],
  i:{y:"A setback out of nowhere — protect the essentials, lose the blossoms.",c:"A sudden nip to the finances; safeguard the principal, forget the yield.",l:"A chill you did not cause; do not uproot the whole thing — winter passes.",h:"Guard against a sudden cold; keep the constitution warm and low.",e:"A project frosts over; salvage the core and wait for a better season."}},
 {n:13, lv:"上上", cn:["金鸡三唱晓光新","万里晴空瑞气生","好把心香酬夙愿","从教福至喜盈门"],
  py:["jīn jī sān chàng xiǎo guāng xīn","wàn lǐ qíng kōng ruì qì shēng","hǎo bǎ xīn xiāng chóu sù yuàn","cóng jiào fú zhì xǐ yíng mén"],
  en:["The golden cock crows thrice; the dawn light is made new;","ten thousand miles of clear sky breed an auspicious air.","Take the incense of your heart and repay the old vow —","and let fortune arrive, and joy fill the doorway."],
  i:{y:"A fresh, bright beginning; the long night is decisively over.",c:"New income opens with the dawn; act on the first light.",l:"A vow kept brings joy home; gratitude sweetens the bond.",h:"Renewed energy at daybreak; early rising suits you now.",e:"A new post or new phase begins under a lucky sky — say yes."}},
 {n:14, lv:"中", cn:["一叶轻舟泛碧波","中流风顺未为多","劝君牢把船头稳","过了滩头是太和"],
  py:["yī yè qīng zhōu fàn bì bō","zhōng liú fēng shùn wèi wéi duō","quàn jūn láo bǎ chuán tóu wěn","guò le tān tóu shì tài hé"],
  en:["A single leaf of a boat rides the jade-green swell;","midstream the wind is fair, but not by very much.","I counsel you: keep a firm hand on the prow —","past the rapids' head lies great and level calm."],
  i:{y:"You are through the worst but not yet clear; steadiness is everything.",c:"A modest tailwind — do not overload the boat.",l:"Smooth enough if you stop rocking it; hold course.",h:"Improving; avoid the one indulgence that could capsize you.",e:"The rapids are nearly behind — grip the wheel, do not celebrate early."}},
 {n:15, lv:"上吉", cn:["云梯稳步上蟾宫","折得高枝第一红","自是辛勤天不负","桂香初动月明中"],
  py:["yún tī wěn bù shàng chán gōng","zhé dé gāo zhī dì yī hóng","zì shì xīn qín tiān bù fù","guì xiāng chū dòng yuè míng zhōng"],
  en:["Up the cloud-ladder, sure of step, to the moon's palace;","you break the high branch, the first and reddest bloom.","Because you toiled, heaven does not turn its back —","the cassia's scent first stirs in the bright moonlight."],
  i:{y:"Diligence is rewarded exactly; the climb pays at the top.",c:"Earned money, arriving on merit — clean and well-timed.",l:"You reach the one held highest; the effort was seen and answered.",h:"Discipline shows its fruit; the regimen is working, continue.",e:"A high honor within reach — stretch, and the branch is yours."}},
 {n:16, lv:"下", cn:["浮云蔽日暗东西","道路茫茫欲问谁","且守寸心归澹泊","莫将泥足陷深泥"],
  py:["fú yún bì rì àn dōng xī","dào lù máng máng yù wèn shuí","qiě shǒu cùn xīn guī dàn bó","mò jiāng ní zú xiàn shēn ní"],
  en:["Drifting cloud blots the sun; east and west go dark;","the road runs on and on — of whom would you even ask?","Keep, for now, the inch of your heart in plain quiet,","and do not let a muddied foot sink into deeper mire."],
  i:{y:"Direction is lost; do less, not more, until the sun returns.",c:"Avoid new commitments — one wrong step drags in the next.",l:"Confusion on both sides; silence is kinder than a muddled word.",h:"Fatigue clouds judgment; simplify, rest, do not self-diagnose.",e:"No clear path — decline the tangled offer rather than sink into it."}},
 {n:17, lv:"上上", cn:["枯枝再遇好春回","嫩绿新红满绿苔","昔日尘埃今日扫","一门喜气自天来"],
  py:["kū zhī zài yù hǎo chūn huí","nèn lǜ xīn hóng mǎn lǜ tái","xī rì chén āi jīn rì sǎo","yī mén xǐ qì zì tiān lái"],
  en:["The bare branch meets, once more, a kind returning spring;","tender green and new red crowd the mossy stone.","The dust of former days is swept away today,","and a household's joy comes down straight from heaven."],
  i:{y:"A full renewal; what looked finished revives with force.",c:"Old dust cleared, new growth — finances turn green again.",l:"Reconciliation and fresh warmth arrive together.",h:"Recovery is decisive now; the constitution rebuilds quickly.",e:"A fresh mandate sweeps out the old troubles — embrace the reset."}},
 {n:18, lv:"中", cn:["月到中秋分外明","无端偏被薄云侵","好将心事从容看","云散依然月满庭"],
  py:["yuè dào zhōng qiū fèn wài míng","wú duān piān bèi bó yún qīn","hǎo jiāng xīn shì cóng róng kàn","yún sàn yī rán yuè mǎn tíng"],
  en:["The moon at mid-autumn is bright beyond all others,","yet for no reason a thin cloud comes to trespass on it.","Better to look on your heart's affairs unhurried —","the cloud disperses, and the moon still floods the court."],
  i:{y:"A temporary shadow over something essentially good; wait it out.",c:"A brief dip, not a loss; the fundamentals are sound.",l:"A small misunderstanding veils real affection — let it pass.",h:"A passing symptom over a strong base; calm is the cure.",e:"A minor obstruction dims a good position — it clears on its own."}},
 {n:19, lv:"下", cn:["风急天寒雁失群","孤鸿哀唳向黄昏","劝君暂敛冲天翼","待到春回自有恩"],
  py:["fēng jí tiān hán yàn shī qún","gū hóng āi lì xiàng huáng hūn","quàn jūn zàn liǎn chōng tiān yì","dài dào chūn huí zì yǒu ēn"],
  en:["Wind sharp, sky cold, the wild goose loses the flock;","the lone bird cries its grief into the dusk.","I counsel you: fold, for now, the sky-storming wing —","wait for spring's return and kindness comes of itself."],
  i:{y:"Isolation and cold; this is a season to withdraw, not to fly.",c:"Cut losses and huddle; the lean stretch is real but not forever.",l:"Loneliness now; do not cry out — the flock regathers in spring.",h:"Guard warmth and rest; the body is depleted, not broken.",e:"Retract ambition briefly; grand moves fail in this wind."}},
 {n:20, lv:"上吉", cn:["桃李逢时正满枝","东风送暖到寒溪","劝君趁此和风便","好整归鞭莫太迟"],
  py:["táo lǐ féng shí zhèng mǎn zhī","dōng fēng sòng nuǎn dào hán xī","quàn jūn chèn cǐ hé fēng biàn","hǎo zhěng guī biān mò tài chí"],
  en:["Peach and plum, meeting their hour, crowd every branch;","the east wind carries warmth down to the cold stream.","I counsel you: take this gentle wind while it lasts —","ready the homeward whip, and do not be too slow."],
  i:{y:"A ripe, favorable window — act inside it, do not dawdle.",c:"The moment to collect or invest is now; delay costs the gain.",l:"The season is right to speak or return; move before it cools.",h:"A good spell for treatment or travel; take it now.",e:"Seize the opening promptly — the warm wind will not wait."}},
 {n:21, lv:"上上", cn:["宝镜重磨照旧妆","菱花再现喜非常","从今物我皆无碍","一片冰心彻底光"],
  py:["bǎo jìng chóng mó zhào jiù zhuāng","líng huā zài xiàn xǐ fēi cháng","cóng jīn wù wǒ jiē wú ài","yī piàn bīng xīn chè dǐ guāng"],
  en:["The treasured mirror, ground again, reflects the old face;","the water-chestnut flower reappears — joy beyond measure.","From now, self and world are without obstruction,","and one piece of an ice-clear heart shines all the way through."],
  i:{y:"Clarity restored; what was clouded between you and the world clears.",c:"A blocked matter is unblocked — accounts reconcile cleanly.",l:"A misunderstanding dissolves; the reflection is true again.",h:"Mind and body align; clarity returns after a foggy stretch.",e:"A stalled matter suddenly reflects true; the path is clean."}},
 {n:22, lv:"中", cn:["蜘蛛结网罥檐前","经营多时枉自忙","若得一朝甘露降","何须辛苦更施张"],
  py:["zhī zhū jié wǎng juàn yán qián","jīng yíng duō shí wǎng zì máng","ruò dé yī zhāo gān lù jiàng","hé xū xīn kǔ gèng shī zhāng"],
  en:["The spider knots its web beneath the eaves,","laboring long and, for all that, busy in vain.","If but one morning the sweet dew comes down,","why toil to stretch the threads any wider?"],
  i:{y:"Effort has outrun result; wait for grace, not more striving.",c:"Over-engineering the plan wastes you; simplify and let it settle.",l:"You are trying too hard — ease off, let it come to you.",h:"Overexertion is the problem; rest is the missing ingredient.",e:"Stop expanding the scheme; consolidate and wait for the break."}},
 {n:23, lv:"下", cn:["虎落平阳被犬欺","蛟龙失水困沙泥","劝君且忍胸中气","留取青山待长时"],
  py:["hǔ luò píng yáng bèi quǎn qī","jiāo lóng shī shuǐ kùn shā ní","quàn jūn qiě rěn xiōng zhōng qì","liú qǔ qīng shān dài zhǎng shí"],
  en:["The tiger, fallen to the flatland, is bullied by dogs;","the river-dragon, out of water, is stuck in the silt.","I counsel you: swallow, for now, the anger in the chest —","keep the green mountain, and bide the longer time."],
  i:{y:"Your strength counts for nothing on this ground; endure, do not fight.",c:"A powerful position is temporarily grounded — preserve capital.",l:"You are undervalued by present company; wait for your own element.",h:"Depleted and out of your element; restore, do not exert.",e:"Out of your depth or misplaced — swallow pride, keep resources, wait."}},
 {n:24, lv:"上吉", cn:["久旱逢甘雨一犁","田园处处发新枝","辛勤自有秋成日","仓廪盈盈庆有余"],
  py:["jiǔ hàn féng gān yǔ yī lí","tián yuán chù chù fā xīn zhī","xīn qín zì yǒu qiū chéng rì","cāng lǐn yíng yíng qìng yǒu yú"],
  en:["Long drought meets sweet rain, enough for one plough's furrow;","across the fields, everywhere, new shoots put out.","Diligence will have its day of autumn harvest —","the granaries brim, and there is surplus to celebrate."],
  i:{y:"Relief arrives and rewards the patient work you kept up.",c:"A dry spell ends in real yield; the harvest is coming, tend it.",l:"Warmth returns after a barren stretch; the ground is fertile again.",h:"Vitality is watered and returning; keep the healthy habit.",e:"Sustained effort now visibly pays — expect a full, surplus season."}},
 {n:25, lv:"中", cn:["路逢岔口两三条","未识何方是坦途","莫听旁人闲指点","问心一寸自分毫"],
  py:["lù féng chà kǒu liǎng sān tiáo","wèi shí hé fāng shì tǎn tú","mò tīng páng rén xián zhǐ diǎn","wèn xīn yī cùn zì fēn háo"],
  en:["The road forks into two or three ways at once,","and which of them runs smooth you cannot yet tell.","Do not heed the idle pointing of bystanders —","ask the inch of your own heart; it knows to the hair."],
  i:{y:"A crossroads with no obvious right turn — trust your own read.",c:"Conflicting advice abounds; decide by your own numbers, not rumor.",l:"Others' opinions confuse a private matter; consult your heart alone.",h:"Too many outside voices; follow your own steady sense.",e:"A choice between paths — ignore the noise, choose by conviction."}},
 {n:26, lv:"下", cn:["满船珍宝欲还乡","偏遇中流风浪狂","不是有缘终不失","且抛什物救危樯"],
  py:["mǎn chuán zhēn bǎo yù huán xiāng","piān yù zhōng liú fēng làng kuáng","bù shì yǒu yuán zhōng bù shī","qiě pāo shí wù jiù wēi qiáng"],
  en:["A boat full of treasure, meaning to sail home,","meets, of all places midstream, the wind gone wild.","What is truly fated will not, in the end, be lost —","so throw the goods overboard and save the failing mast."],
  i:{y:"To keep what matters, you must let some things go now.",c:"A loss is coming — cut the cargo to save the vessel.",l:"Sacrifice a smaller attachment to protect the essential bond.",h:"Drop the lesser commitments; the body must not be lost with them.",e:"Shed the project's dead weight fast, or the whole venture founders."}},
 {n:27, lv:"上上", cn:["凤凰来仪集梧桐","瑞霭祥光满太空","积善之家多庆事","儿孙个个显门风"],
  py:["fèng huáng lái yí jí wú tóng","ruì ǎi xiáng guāng mǎn tài kōng","jī shàn zhī jiā duō qìng shì","ér sūn gè gè xiǎn mén fēng"],
  en:["The phoenix comes in stately measure to the wutong tree;","auspicious mist and lucky light fill all the sky.","The house that stored up kindness has much to celebrate —","its sons and grandsons, each of them, honor the name."],
  i:{y:"A rare and blessed convergence; good you have stored returns manifold.",c:"Abundance that reflects long integrity — wealth with honor.",l:"A distinguished, blessed match; families rejoice together.",h:"Deep well-being rooted in a good life; flourishing, not fragile.",e:"High distinction earned by character — your name rises, cleanly."}},
 {n:28, lv:"上吉", cn:["月出东山夜色清","一轮皎洁照人明","向来暗室亏心事","从此堂堂表里清"],
  py:["yuè chū dōng shān yè sè qīng","yī lún jiǎo jié zhào rén míng","xiàng lái àn shì kuī xīn shì","cóng cǐ táng táng biǎo lǐ qīng"],
  en:["The moon lifts from the eastern hill; the night runs clear;","one round, spotless disc lights a person plain.","Whatever guilty business was done in the dark room,","from now stands upright — clear without and within."],
  i:{y:"Hidden things come to light in your favor; honesty is rewarded.",c:"A murky account clarifies; what was owed is set right.",l:"Trust is restored; nothing hidden remains between you.",h:"A shadowed worry proves benign; clarity brings ease.",e:"A matter under suspicion clears; your name stands upright."}},
 {n:29, lv:"中", cn:["玉在匣中光未露","剑藏鞘里锷犹寒","时人不识凌云器","且向尘埃自静观"],
  py:["yù zài xiá zhōng guāng wèi lù","jiàn cáng qiào lǐ è yóu hán","shí rén bù shí líng yún qì","qiě xiàng chén āi zì jìng guān"],
  en:["The jade in its box has not yet let out its light;","the sword sheathed in its scabbard keeps a cold edge still.","The people of the age do not know the cloud-piercing tool —","so, amid the dust, keep your own quiet watch."],
  i:{y:"Your time is not yet; readiness in obscurity is the task.",c:"Latent value, not liquid — do not force it to market early.",l:"You are underestimated; the right person will sense the edge.",h:"Reserve your strength; do not unsheathe it on small things.",e:"Talent unrecognized for now — stay sharp, stay patient."}},
 {n:30, lv:"下", cn:["枯藤老树暮鸦啼","古道西风瘦马嘶","断肠人在天涯路","且宽怀抱莫沉迷"],
  py:["kū téng lǎo shù mù yā tí","gǔ dào xī fēng shòu mǎ sī","duàn cháng rén zài tiān yá lù","qiě kuān huái bào mò chén mí"],
  en:["Withered vine, old tree, a crow calling at dusk;","the ancient road, west wind, a thin horse neighing.","The heartbroken one is far on the road to the sky's edge —","loosen the grip of your grief; do not drown in it."],
  i:{y:"A bleak, lonely stretch; the counsel is endurance, not despair.",c:"Lean and comfortless; conserve, do not gamble to escape it.",l:"Distance and sorrow; hold the heart open, do not close it for good.",h:"Low spirits weigh on the body; movement and light are needed.",e:"A hard, thankless road — press on soberly; the edge is not the end."}},
 {n:31, lv:"上上", cn:["彩凤衔书降九天","一朝好事到门前","从前疑虑今皆散","稳步青云直上天"],
  py:["cǎi fèng xián shū jiàng jiǔ tiān","yī zhāo hǎo shì dào mén qián","cóng qián yí lǜ jīn jiē sàn","wěn bù qīng yún zhí shàng tiān"],
  en:["The bright phoenix, a letter in its beak, descends the sky;","in a single morning good tidings reach your door.","The doubts you carried before have all dispersed —","sure of step, you climb the blue cloud straight to heaven."],
  i:{y:"Excellent news arrives suddenly; lingering doubts are answered.",c:"A favorable message brings gain; the deal is blessed.",l:"A joyful announcement; the answer you feared is a yes.",h:"Worry lifts and vigor with it; the report is good.",e:"An offer or acceptance letter comes — your ascent is confirmed."}},
 {n:32, lv:"中", cn:["田中禾稼正堪耘","莫惜辛勤莫惜身","若使中间生懈怠","秋来空自叹无成"],
  py:["tián zhōng hé jià zhèng kān yún","mò xī xīn qín mò xī shēn","ruò shǐ zhōng jiān shēng xiè dài","qiū lái kōng zì tàn wú chéng"],
  en:["The grain in the field is just at the weeding stage;","do not spare the labor, do not spare yourself.","If, halfway through, you let a slackness in,","come autumn you will sigh, alone, at nothing gained."],
  i:{y:"The outcome depends entirely on whether you keep at it now.",c:"No gain without continued tending; slack off and lose the crop.",l:"A bond mid-cultivation; neglect now undoes the whole season.",h:"Consistency is the medicine; a lapse now sets you back.",e:"You are at the crucial middle — sustain effort or forfeit the harvest."}},
 {n:33, lv:"上吉", cn:["行船已到顺风时","一路清波稳泛之","莫问前村深与浅","自然稳载到天涯"],
  py:["xíng chuán yǐ dào shùn fēng shí","yī lù qīng bō wěn fàn zhī","mò wèn qián cūn shēn yǔ qiǎn","zì rán wěn zài dào tiān yá"],
  en:["The sailing has come round to the hour of a following wind;","all the way the clear swell bears you smoothly on.","Do not ask whether the water ahead runs deep or shallow —","of itself it will carry you safe to the world's edge."],
  i:{y:"You have caught the tailwind; trust momentum, stop over-checking.",c:"Smooth returns — do not second-guess a plan that is working.",l:"The relationship glides easily now; enjoy it, do not test it.",h:"Steady improvement; let the recovery carry itself.",e:"The wind is with you — commit fully and go the distance."}},
 {n:34, lv:"下", cn:["镜破难圆终有痕","弦断重续韵非真","劝君好自寻新路","莫向残花更问春"],
  py:["jìng pò nán yuán zhōng yǒu hén","xián duàn chóng xù yùn fēi zhēn","quàn jūn hǎo zì xún xīn lù","mò xiàng cán huā gèng wèn chūn"],
  en:["A broken mirror, hard to round, keeps its seam in the end;","a snapped string, rejoined, sounds a note that is not true.","I counsel you: go and find, of yourself, a new road —","and do not ask the ruined flower for another spring."],
  i:{y:"Something is finished; forcing it whole again only shows the crack.",c:"A soured deal will not recover — write it off and start fresh.",l:"A break that will not rejoin cleanly; better a new road than a false note.",h:"An old approach has failed; change methods rather than repeat.",e:"Stop repairing the broken thing; build a new one instead."}},
 {n:35, lv:"中", cn:["潮生潮落海门宽","得意休忘失意难","但把此心平似水","自然到处得心安"],
  py:["cháo shēng cháo luò hǎi mén kuān","dé yì xiū wàng shī yì nán","dàn bǎ cǐ xīn píng sì shuǐ","zì rán dào chù dé xīn ān"],
  en:["Tide rises, tide falls; the sea-gate is wide;","in triumph do not forget how hard the low days were.","Only keep this heart as level as the water,","and everywhere, of itself, you find peace of mind."],
  i:{y:"Fortunes ebb and flow — equanimity is the whole practice now.",c:"Up and down; steadiness of temperament matters more than the swing.",l:"Keep an even keel through the tides and the bond holds.",h:"Balance over extremes; a level life keeps the body level.",e:"Neither high nor low lasts — stay even and you do well anywhere."}},
 {n:36, lv:"上上", cn:["一轮红日上天心","万里山河尽照明","从此前程无暗昧","光风霁月任君行"],
  py:["yī lún hóng rì shàng tiān xīn","wàn lǐ shān hé jìn zhào míng","cóng cǐ qián chéng wú àn mèi","guāng fēng jì yuè rèn jūn xíng"],
  en:["One red sun climbs to the very heart of the sky;","ten thousand miles of hill and river are lit throughout.","From now the road ahead holds no dark or doubt —","bright wind, clear moon: go where you please."],
  i:{y:"Full daylight on your affairs; nothing hidden obstructs you.",c:"Transparent, thriving finances — act openly and prosper.",l:"An open, honest love with nothing shadowed; go forward freely.",h:"Radiant health; the whole system is lit and working.",e:"A commanding position with clear sight — the field is yours."}},
 {n:37, lv:"中", cn:["栽花种竹待春来","莫向东风苦问开","但得根深枝叶茂","自然时至满庭栽"],
  py:["zāi huā zhòng zhú dài chūn lái","mò xiàng dōng fēng kǔ wèn kāi","dàn dé gēn shēn zhī yè mào","zì rán shí zhì mǎn tíng zāi"],
  en:["Plant the flowers, set the bamboo, and wait for spring;","do not bitterly ask the east wind when they will bloom.","Only let the root go deep, the leaf grow lush,","and in its own time the whole court fills with green."],
  i:{y:"Build the roots now; the flowering is not something you can rush.",c:"Invest in fundamentals; returns come when the base is deep.",l:"Tend the relationship's roots patiently; blossoms follow.",h:"Deep habits over quick fixes; the body rewards the long view.",e:"Lay a strong foundation now; visible success arrives on schedule."}},
 {n:38, lv:"下", cn:["乌云蔽月黑漫漫","行到山穷水尽间","莫谓此身无出路","回头也是一重天"],
  py:["wū yún bì yuè hēi màn màn","xíng dào shān qióng shuǐ jìn jiān","mò wèi cǐ shēn wú chū lù","huí tóu yě shì yī chóng tiān"],
  en:["Black cloud blots the moon; the dark runs on and on;","you have walked to where the hills give out and the water ends.","Do not say there is no way out for you —","turn your head, and that too is a whole new sky."],
  i:{y:"A dead end — but the exit is behind you, in what you refused to reconsider.",c:"The forward plan is exhausted; the answer is a reversal, not a push.",l:"The current course has no future; turning back opens another sky.",h:"Stop the failing regimen; the relief is in the opposite direction.",e:"The road ahead is blocked — retrace, and a different route appears."}},
 {n:39, lv:"上吉", cn:["喜逢良匠遇良材","大厦峥嵘次第开","但使规绳无少失","擎天柱石栋梁材"],
  py:["xǐ féng liáng jiàng yù liáng cái","dà shà zhēng róng cì dì kāi","dàn shǐ guī shéng wú shǎo shī","qíng tiān zhù shí dòng liáng cái"],
  en:["Glad meeting: a fine craftsman finds fine timber;","the great hall, towering, rises stage by stage.","Only let the compass and line be nowhere off,","and here is a sky-holding pillar, a roof-beam of a person."],
  i:{y:"The right people and materials converge — big things can be built.",c:"A well-matched partnership yields substantial, structural gains.",l:"A strong, complementary pairing; build something lasting together.",h:"A sound frame; keep the disciplines exact and it holds for years.",e:"You and the opportunity fit — execute precisely and become foundational."}},
 {n:40, lv:"中", cn:["守株待兔枉劳心","旧日成规未可循","若肯随时改弦辙","自然处处遇知音"],
  py:["shǒu zhū dài tù wǎng láo xīn","jiù rì chéng guī wèi kě xún","ruò kěn suí shí gǎi xián zhé","zì rán chù chù yù zhī yīn"],
  en:["Guarding the stump for the hare wears out the mind in vain;","the fixed rules of former days cannot be followed now.","If you are willing, with the times, to change string and track,","then everywhere, of itself, you meet a kindred ear."],
  i:{y:"The old method has stopped working; adapt and doors reopen.",c:"Yesterday's strategy will not repeat — update it and gains return.",l:"Repeating old patterns fails; change your approach to be understood.",h:"A new regimen is needed; the old one has run its course.",e:"Do not wait by the stump — revise the plan and allies appear."}},
 {n:41, lv:"上上", cn:["苦尽甘来分外甜","一轮明月照心田","从前多少艰难事","尽付东流化作烟"],
  py:["kǔ jìn gān lái fèn wài tián","yī lún míng yuè zhào xīn tián","cóng qián duō shǎo jiān nán shì","jìn fù dōng liú huà zuò yān"],
  en:["Bitterness spent, the sweet arrives, sweeter than ordinary;","one bright moon shines on the field of the heart.","However many hard things there were before,","give them to the east-flowing stream to turn to smoke."],
  i:{y:"The suffering is genuinely over; release the past and receive the good.",c:"Hardship converts to gain; what you endured is repaid sweetly.",l:"After a long strain, ease and sweetness — let old grievances dissolve.",h:"A hard illness lifts; the body sweetens back into itself.",e:"The difficult phase closes with reward; forgive the road that got you here."}},
 {n:42, lv:"下", cn:["贪看天边雁一行","不知脚下路多歧","劝君收拾贪高眼","且顾眼前莫远驰"],
  py:["tān kàn tiān biān yàn yī háng","bù zhī jiǎo xià lù duō qí","quàn jūn shōu shí tān gāo yǎn","qiě gù yǎn qián mò yuǎn chí"],
  en:["So greedy to watch the geese in a line at the sky's edge","you do not notice the road at your feet runs full of forks.","I counsel you: gather in that high-reaching eye,","mind what is in front of you, and do not race off far."],
  i:{y:"Reaching for the distant thing, you are about to trip on the near one.",c:"Grand ambitions distract from a present leak — fix what is underfoot.",l:"Idealizing someone far off, you neglect what is real and here.",h:"Chasing a big goal, you ignore a small ailment — tend it first.",e:"Rein in the moonshot; the immediate task is where you will stumble."}},
 {n:43, lv:"上吉", cn:["病去身安喜自加","枯杨发叶又开花","从今莫作寻常看","福寿绵绵到我家"],
  py:["bìng qù shēn ān xǐ zì jiā","kū yáng fā yè yòu kāi huā","cóng jīn mò zuò xún cháng kàn","fú shòu mián mián dào wǒ jiā"],
  en:["The sickness gone, the body eased, joy adds of itself;","the withered willow puts out leaf and flowers once more.","From now, do not regard it as an ordinary thing —","fortune and long life come, unbroken, to my house."],
  i:{y:"Recovery and relief; treat this reprieve as the gift it is.",c:"Money follows the returning health; ease breeds increase.",l:"Warmth revives after a hard patch; the bond blossoms late.",h:"The turning point in an illness — strength and years return.",e:"Energy restored, work flourishes again; do not take it for granted."}},
 {n:44, lv:"中", cn:["云中月色时圆缺","世上人情自浅深","且把是非收拾起","静看花开花落心"],
  py:["yún zhōng yuè sè shí yuán quē","shì shàng rén qíng zì qiǎn shēn","qiě bǎ shì fēi shōu shí qǐ","jìng kàn huā kāi huā luò xīn"],
  en:["The moon's color in the cloud is now full, now waning;","the feelings of the world run, of themselves, shallow or deep.","For now, gather up the right-and-wrong and put it away,","and watch, with a quiet heart, the flowers open and fall."],
  i:{y:"Fortunes and loyalties wax and wane — detach from the drama.",c:"Neither loss nor gain; let go of disputes over small sums.",l:"People's warmth varies; do not keep score, watch with a calm heart.",h:"Cycles of better and worse; equanimity steadies the whole.",e:"Office politics ebb and flow — step back from the right-and-wrong."}},
 {n:45, lv:"下", cn:["一时错认路傍花","惹得游蜂扰岁华","及早回头修正业","免教后悔怨天涯"],
  py:["yī shí cuò rèn lù bàng huā","rě dé yóu fēng rǎo suì huá","jí zǎo huí tóu xiū zhèng yè","miǎn jiào hòu huǐ yuàn tiān yá"],
  en:["For a moment you mistook the roadside flower for your own,","and drew the wandering bees to trouble your good years.","Turn back early and set your proper work in order,","lest, later, you regret it and blame the ends of the earth."],
  i:{y:"A tempting detour will cost you; correct course before it is expensive.",c:"A dubious opportunity draws trouble — withdraw before you are stung.",l:"A wrong attraction invites chaos; return to what is truly yours.",h:"An indulgence is harming you; stop it early, not after the damage.",e:"A flashy side-venture distracts from your real work — refocus now."}},
 {n:46, lv:"上上", cn:["天开黄道喜非常","到处逢人尽吉祥","若问功名与财禄","双双如意满门墙"],
  py:["tiān kāi huáng dào xǐ fēi cháng","dào chù féng rén jìn jí xiáng","ruò wèn gōng míng yǔ cái lù","shuāng shuāng rú yì mǎn mén qiáng"],
  en:["Heaven opens an auspicious day — joy beyond the common;","everywhere you go, everyone you meet is a good omen.","If you ask after honor and after wealth —","both together, just as you wished, fill your house."],
  i:{y:"A day when everything aligns; act on the big things now.",c:"Wealth and recognition arrive together — rare and generous timing.",l:"An especially blessed moment for union or proposal.",h:"Everything favors well-being; a fine time for any undertaking.",e:"Honor and reward come as a pair — seize the golden day."}},
 {n:47, lv:"中", cn:["晓来风雨暗园林","吹落红英满地深","莫惜残花零落尽","明年依旧发新林"],
  py:["xiǎo lái fēng yǔ àn yuán lín","chuī luò hóng yīng mǎn dì shēn","mò xī cán huā líng luò jìn","míng nián yī jiù fā xīn lín"],
  en:["Dawn brings wind and rain that darken the garden grove;","the red petals, blown down, lie deep across the ground.","Do not grieve the ruined blossoms falling to the last —","next year, as ever, the grove puts out new growth."],
  i:{y:"A loss that is really a clearing; the cycle will renew.",c:"A downturn now; do not mourn it — next season regrows.",l:"An ending makes room; grieve lightly, the heart renews.",h:"A rough patch passes; the body, like the grove, comes back.",e:"A setback clears old growth — next cycle brings fresh opportunity."}},
 {n:48, lv:"上吉", cn:["夜梦分明喜信来","一家欢笑乐悠哉","从前多少愁眉事","尽逐春风笑口开"],
  py:["yè mèng fēn míng xǐ xìn lái","yī jiā huān xiào lè yōu zāi","cóng qián duō shǎo chóu méi shì","jìn zhú chūn fēng xiào kǒu kāi"],
  en:["The night's dream was clear: glad news is on its way;","a whole house laughing, joy at its ease.","However many brow-furrowing worries there were before,","all chase off on the spring wind, and the mouth opens in a smile."],
  i:{y:"Good news you sensed is confirmed; worries lift into laughter.",c:"A happy financial turn brightens the whole household.",l:"Joyful tidings for love or family; celebration is warranted.",h:"Anxiety lifts and the body eases; the mood itself is medicine.",e:"A welcome announcement; the burdens of the last stretch dissolve."}}
];
